
import json
import re

path = r"c:\Users\amadej\Desktop\moja-spletna-stran\flowstackai.github.io\dashboard.html"

# Correct Content Data with proper emojis and characters
content_data = {
    "en": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS Builder', "shortDesc": 'Create and scale software products that generate recurring revenue.', "fullDesc": 'Software as a Service (SaaS) is the gold standard of digital income. Learn how to identify market gaps, build using no-code or code tools, and scale a subscription-based business.', "steps": [ { "title": 'Ideation', "desc": 'Find profitable problems to solve.' }, { "title": 'MVP Build', "desc": 'Launch a working prototype fast.' }, { "title": 'Scale', "desc": 'Acquire users and recurring revenue.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Master the art of persuasion to sell anything with words.', "fullDesc": 'Good copy makes millions. Learn the psychology behind persuasion, how to write landing pages, emails, and ads that convert strangers into customers for high fees.', "steps": [ { "title": 'Psychology', "desc": 'Understand what drives action.' }, { "title": 'Frameworks', "desc": 'Master proven writing structures.' }, { "title": 'Client Acquisition', "desc": 'Land high-paying retainers.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Digital Marketing', "shortDesc": 'Run profitable ads and manage growth for businesses.', "fullDesc": 'Every business needs more customers. Start an agency (SMMA) helping brands grow through Facebook Ads, TikTok Ads, and Google Ads. High demand, scalable service.', "steps": [ { "title": 'Ad Strategy', "desc": 'Learn to run profitable campaigns.' }, { "title": 'Service Delivery', "desc": 'Generate leads for clients.' }, { "title": 'Agency Growth', "desc": 'Build a team to fulfilling work.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Financial Trading', "shortDesc": 'Analyze markets and trade Crypto, Forex, or Indices.', "fullDesc": 'Master key technical analysis concepts to navigate financial markets. Learn risk management, psychology, and strategies to profit from market movements independently.', "steps": [ { "title": 'Analysis', "desc": 'Read charts and market structure.' }, { "title": 'Risk Mgmt', "desc": 'Protect your capital first.' }, { "title": 'Execution', "desc": 'Place high-probability trades.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Content Creation', "shortDesc": 'Build a personal brand and monetize your audience.', "fullDesc": 'Attention is the new currency. Learn how to create viral short-form content, build a loyal following, and monetize through sponsorships, affiliates, or your own products.', "steps": [ { "title": 'Viral Scripts', "desc": 'Hook viewers instantly.' }, { "title": 'Production', "desc": 'Film and edit high-quality clips.' }, { "title": 'Monetization', "desc": 'Turn views into income.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Sell physical products globally without holding inventory.', "fullDesc": 'Start a dropshipping or BRANDED e-commerce store. Learn product research, supplier relations, and how to build a converting storefront on Shopify.', "steps": [ { "title": 'Product Hunt', "desc": 'Find winning products.' }, { "title": 'Store Build', "desc": 'Design a high-converting site.' }, { "title": 'Launch', "desc": 'Drive traffic and fulfill orders.' } ] }
    ],
    "sl": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS Razvijalec', "shortDesc": ' ustvari in prodajaj programsko opremo z meseÄŤno naroÄŤnino.', "fullDesc": 'Software as a Service (SaaS) je zlati standard digitalnega zasluĹľka. NauÄŤi se prepoznati trĹľne priloĹľnosti, zgraditi reĹˇitev (no-code ali koda) in skalirati posel.', "steps": [ { "title": 'Ideja', "desc": 'Najdi dobiÄŤkonosne probleme.' }, { "title": 'MVP Izdelava', "desc": 'Hitro lansiraj delujoÄŤ prototip.' }, { "title": 'Rast', "desc": 'Pridobi uporabnike in redne prihodke.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Obvladaj umetnost prepriÄŤevanja in prodajaj z besedami.', "fullDesc": 'Dobra besedila prinaĹˇajo milijone. Spoznaj psihologijo prodaje, kako pisati pristajalne strani, emaile in oglase, ki obiskovalce spremenijo v kupce.', "steps": [ { "title": 'Psihologija', "desc": 'Razumej, kaj sproĹľi akcijo.' }, { "title": 'Formule', "desc": 'Uporabi preverjene strukture pisanja.' }, { "title": 'Pridobivanje strank', "desc": 'Dobi visoko plaÄŤane projekte.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Digitalni Marketing', "shortDesc": 'Upravljaj dobiÄŤkonosne oglase za podjetja (SMMA).', "fullDesc": 'Vsako podjetje potrebuje veÄŤ strank. Odpri agencijo in pomagaj znamkam rasti s Facebook, TikTok in Google oglasi. Visoko povpraĹˇevanje, skalabilno.', "steps": [ { "title": 'Strategija', "desc": 'NauÄŤi se voditi profitabilne kampanje.' }, { "title": 'Rezultati', "desc": 'Generiraj leade za stranke.' }, { "title": 'Rast Agencije', "desc": 'Zgradi ekipo in delegiraj delo.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Trading', "shortDesc": 'Analiziraj trge in trguj s Kripto, Forex ali Indeksi.', "fullDesc": 'Obvladaj tehniÄŤno analizo in finanÄŤne trge. NauÄŤi se obvladovanja tveganja, psihologije in strategij za samostojno profitabilno trgovanje.', "steps": [ { "title": 'Analiza', "desc": 'Branje grafov in trĹľne strukture.' }, { "title": 'Tveganje', "desc": 'Najprej zaĹˇÄŤiti svoj kapital.' }, { "title": 'Izvedba', "desc": 'Izvajaj posle z visoko verjetnostjo.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Ustvarjanje Vsebin', "shortDesc": 'Zgradi osebno znamko in monetiziraj obÄŤinstvo.', "fullDesc": 'Pozornost je nova valuta. NauÄŤi se ustvarjati viralne kratke videe, zgraditi zvesto skupnost in sluĹľiti s sponzorstvi ali lastnimi produkti.', "steps": [ { "title": 'Viralni Skripti', "desc": 'Takoj pritegni gledalca.' }, { "title": 'Produkcija', "desc": 'Snemaj in montiraj kvalitetne videe.' }, { "title": 'Monetizacija', "desc": 'Spremeni oglede v prihodke.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Prodajaj fiziÄŤne izdelke brez skladiĹˇÄŤenja (Dropshipping).', "fullDesc": 'ZaÄŤni svojo spletno trgovino. NauÄŤi se raziskave produktov, sodelovanja z dobavitelji in postavitve Shopify trgovine, ki dejansko prodaja.', "steps": [ { "title": 'Iskanje Produktov', "desc": 'Najdi zmagovalne izdelke.' }, { "title": 'Trgovina', "desc": 'Dizajniraj prodajno stran.' }, { "title": 'Lansiranje', "desc": 'Pripelji promet in izpolni naroÄŤila.' } ] }
    ],
    "sq": [
        { "id": 'saas', "icon": 'đź’»', "title": 'NdĂ«rtues SaaS', "shortDesc": 'Krijoni dhe shkallĂ«zoni produkte softuerike qĂ« gjenerojnĂ« tĂ« ardhura tĂ« pĂ«rsĂ«ritura.', "fullDesc": 'Softueri si ShĂ«rbim (SaaS) Ă«shtĂ« standardi i artĂ« i tĂ« ardhurave dixhitale. MĂ«soni si tĂ« identifikoni zbrazĂ«tirat e tregut, tĂ« ndĂ«rtoni duke pĂ«rdorur mjete pa kod ose kod, dhe tĂ« shkallĂ«zoni njĂ« biznes tĂ« bazuar nĂ« abonim.', "steps": [ { "title": 'Ideimi', "desc": 'Gjeni probleme fitimprurĂ«se pĂ«r tĂ« zgjidhur.' }, { "title": 'NdĂ«rtimi i MVP', "desc": 'Lansoni njĂ« prototip qĂ« funksionon shpejt.' }, { "title": 'ShkallĂ«zimi', "desc": 'Fitoni pĂ«rdorues dhe tĂ« ardhura tĂ« pĂ«rsĂ«ritura.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'PĂ«rsosni artin e bindjes pĂ«r tĂ« shitur Ă§do gjĂ« me fjalĂ«.', "fullDesc": 'NjĂ« tekst i mirĂ« bĂ«n miliona. MĂ«soni psikologjinĂ« pas bindjes, si tĂ« shkruani faqe uljeje, email-e dhe reklama qĂ« konvertojnĂ« tĂ« huajt nĂ« klientĂ« pĂ«r tarifa tĂ« larta.', "steps": [ { "title": 'Psikologjia', "desc": 'Kuptoni Ă§farĂ« nxit veprimin.' }, { "title": 'Kornizat', "desc": 'PĂ«rsosni strukturat e provuara tĂ« shkrimit.' }, { "title": 'Marrja e KlientĂ«ve', "desc": 'Siguroni kontrata me pagesĂ« tĂ« lartĂ«.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Marketing Dixhital', "shortDesc": 'Drejtoni reklama fitimprurĂ«se dhe menaxhoni rritjen pĂ«r bizneset.', "fullDesc": 'Ă‡do biznes ka nevojĂ« pĂ«r mĂ« shumĂ« klientĂ«. Filloni njĂ« agjenci (SMMA) duke ndihmuar markat tĂ« rriten pĂ«rmes Facebook Ads, TikTok Ads dhe Google Ads. KĂ«rkesĂ« e lartĂ«, shĂ«rbim i shkallĂ«zueshĂ«m.', "steps": [ { "title": 'Strategjia e Reklamave', "desc": 'MĂ«soni tĂ« drejtoni fushata fitimprurĂ«se.' }, { "title": 'DorĂ«zimi i ShĂ«rbimit', "desc": 'Gjeneroni klientĂ« potencialĂ«.' }, { "title": 'Rritja e AgjencisĂ«', "desc": 'NdĂ«rtoni njĂ« ekip pĂ«r punĂ« pĂ«rmbushĂ«se.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Tregtim Financiar', "shortDesc": 'Analizoni tregjet dhe tregtoni Kripto, Forex ose Indekse.', "fullDesc": 'PĂ«rsosni konceptet kryesore tĂ« analizĂ«s teknike pĂ«r tĂ« lundruar nĂ« tregjet financiare. MĂ«soni menaxhimin e rrezikut, psikologjinĂ« dhe strategjitĂ« pĂ«r tĂ« pĂ«rfituar nga lĂ«vizjet e tregut nĂ« mĂ«nyrĂ« tĂ« pavarur.', "steps": [ { "title": 'Analiza', "desc": 'Lexoni grafikĂ«t dhe strukturĂ«n e tregut.' }, { "title": 'Menaxhimi i Rrezikut', "desc": 'Mbroni kapitalin tuaj sĂ« pari.' }, { "title": 'Ekzekutimi', "desc": 'Vendosni tregti me probabilitet tĂ« lartĂ«.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Krijimi i PĂ«rmbajtjes', "shortDesc": 'NdĂ«rtoni njĂ« markĂ« personale dhe fitoni nga audienca juaj.', "fullDesc": 'VĂ«mendja Ă«shtĂ« valuta e re. MĂ«soni si tĂ« krijoni pĂ«rmbajtje virale nĂ« formĂ« tĂ« shkurtĂ«r, tĂ« ndĂ«rtoni njĂ« ndjekĂ«s besnik dhe tĂ« fitoni pĂ«rmes sponsorizimeve, filialeve ose produkteve tuaja.', "steps": [ { "title": 'SkenarĂ« ViralĂ«', "desc": 'TĂ«rhiqni shikuesit menjĂ«herĂ«.' }, { "title": 'Prodhimi', "desc": 'Filmoni dhe editoni klipe me cilĂ«si tĂ« lartĂ«.' }, { "title": 'Monetizimi', "desc": 'Ktheni shikimet nĂ« tĂ« ardhura.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Shisni produkte fizike globalisht pa mbajtur inventar.', "fullDesc": 'Filloni njĂ« dyqan dropshipping ose tĂ« markuar. MĂ«soni kĂ«rkimin e produkteve, marrĂ«dhĂ«niet me furnitorĂ«t dhe si tĂ« ndĂ«rtoni njĂ« vitrinĂ« konvertuese nĂ« Shopify.', "steps": [ { "title": 'Gjuetia e Produkteve', "desc": 'Gjeni produkte fituese.' }, { "title": 'NdĂ«rtimi i Dyqanit', "desc": 'Dizenjoni njĂ« faqe me konvertim tĂ« lartĂ«.' }, { "title": 'Lansimi', "desc": 'Drejtoni trafikun dhe pĂ«rmbushni porositĂ«.' } ] }
    ],
    "ar": [
        { "id": 'saas', "icon": 'đź’»', "title": 'Ů…Ů†Ř´Ř¦ SaaS', "shortDesc": 'ŘŁŮ†Ř´Ř¦ ŮŮ‚Ů… Ř¨ŘŞŮŘłŮŠŘą Ů…Ů†ŘŞŘ¬Ř§ŘŞ Ř¨Ř±Ů…Ř¬ŮŠŘ© ŘŞŘŻŘ± ŘŻŘ®Ů„Ř§Ů‹ Ů…ŘŞŮŘ±Ř±Ů‹Ř§.', "fullDesc": 'Ř§Ů„Ř¨Ř±Ů…Ř¬ŮŠŘ§ŘŞ ŮŘ®ŘŻŮ…Ř© (SaaS) Ů‡ŮŠ Ř§Ů„Ů…ŘąŮŠŘ§Ř± Ř§Ů„Ř°Ů‡Ř¨ŮŠ Ů„Ů„ŘŻŘ®Ů„ Ř§Ů„Ř±Ů‚Ů…ŮŠ. ŘŞŘąŮ„Ů… ŮŮŠŮŮŠŘ© ŘŞŘ­ŘŻŮŠŘŻ ŮŘ¬ŮŘ§ŘŞ Ř§Ů„ŘłŮŮ‚ŘŚ ŮŘ§Ů„Ř¨Ů†Ř§Řˇ Ř¨Ř§ŘłŘŞŘ®ŘŻŘ§Ů… ŘŁŘŻŮŘ§ŘŞ Ř¨ŘŻŮŮ† ŮŮŘŻ ŘŁŮ Ř¨Ř§Ů„ŮŮŘŻŘŚ ŮŘŞŮŘłŮŠŘą Ů†Ř·Ř§Ů‚ ŘąŮ…Ů„ ŮŠŘąŘŞŮ…ŘŻ ŘąŮ„Ů‰ Ř§Ů„Ř§Ř´ŘŞŘ±Ř§Ů.', "steps": [ { "title": 'ŘŞŮŮŮŠŮ† Ř§Ů„ŮŮŘ±Ř©', "desc": 'Ř§Ř¨Ř­Ř« ŘąŮ† Ů…Ř´Ř§ŮŮ„ Ů…Ř±Ř¨Ř­Ř© Ů„Ř­Ů„Ů‡Ř§.' }, { "title": 'Ř¨Ů†Ř§Řˇ MVP', "desc": 'ŘŁŘ·Ů„Ů‚ Ů†Ů…ŮŘ°Ř¬Ů‹Ř§ ŘŁŮŮ„ŮŠŮ‹Ř§ ŘąŘ§Ů…Ů„Ř§Ů‹ Ř¨ŘłŘ±ŘąŘ©.' }, { "title": 'Ř§Ů„ŘŞŮŘłŘą', "desc": 'Ř§ŮŘŞŘłŘ¨ Ů…ŘłŘŞŘ®ŘŻŮ…ŮŠŮ† ŮŘĄŮŠŘ±Ř§ŘŻŘ§ŘŞ Ů…ŘŞŮŘ±Ř±Ř©.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'ŮŘŞŘ§Ř¨Ř© Ř§Ů„ŘĄŘąŮ„Ř§Ů†Ř§ŘŞ', "shortDesc": 'ŘŁŘŞŮ‚Ů† ŮŮ† Ř§Ů„ŘĄŮ‚Ů†Ř§Řą Ů„Ř¨ŮŠŘą ŘŁŮŠ Ř´ŮŠŘˇ Ř¨Ř§Ů„ŮŮ„Ů…Ř§ŘŞ.', "fullDesc": 'Ř§Ů„Ů†ŘµŮŘµ Ř§Ů„Ř¬ŮŠŘŻŘ© ŘŞŘµŮ†Řą Ř§Ů„Ů…Ů„Ř§ŮŠŮŠŮ†. ŘŞŘąŮ„Ů… ŘąŮ„Ů… Ř§Ů„Ů†ŮŘł ŮŘ±Ř§Řˇ Ř§Ů„ŘĄŮ‚Ů†Ř§ŘąŘŚ ŮŮŮŠŮŮŠŘ© ŮŘŞŘ§Ř¨Ř© ŘµŮŘ­Ř§ŘŞ Ř§Ů„Ů‡Ř¨ŮŘ·ŘŚ ŮŘ±ŘłŘ§Ř¦Ů„ Ř§Ů„Ř¨Ř±ŮŠŘŻ Ř§Ů„ŘĄŮ„ŮŘŞŘ±ŮŮ†ŮŠŘŚ ŮŘ§Ů„ŘĄŘąŮ„Ř§Ů†Ř§ŘŞ Ř§Ů„ŘŞŮŠ ŘŞŘ­ŮŮ„ Ř§Ů„ŘşŘ±Ř¨Ř§Řˇ ŘĄŮ„Ů‰ ŘąŮ…Ů„Ř§Řˇ Ů…Ů‚Ř§Ř¨Ů„ Ř±ŘłŮŮ… ŘąŘ§Ů„ŮŠŘ©.', "steps": [ { "title": 'ŘąŮ„Ů… Ř§Ů„Ů†ŮŘł', "desc": 'Ř§ŮŮ‡Ů… Ů…Ř§ ŮŠŘŻŮŘą Ů„Ř§ŘŞŘ®Ř§Ř° ŘĄŘ¬Ř±Ř§Řˇ.' }, { "title": 'Ř§Ů„ŘŁŘ·Ř±', "desc": 'ŘŁŘŞŮ‚Ů† Ů‡ŮŠŘ§ŮŮ„ Ř§Ů„ŮŘŞŘ§Ř¨Ř© Ř§Ů„Ů…Ř«Ř¨ŘŞŘ©.' }, { "title": 'Ř§ŮŘŞŘłŘ§Ř¨ Ř§Ů„ŘąŮ…Ů„Ř§Řˇ', "desc": 'Ř§Ř­ŘµŮ„ ŘąŮ„Ů‰ ŘąŮ‚ŮŘŻ ŘąŘ§Ů„ŮŠŘ© Ř§Ů„ŘŁŘ¬Ř±.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Ř§Ů„ŘŞŘłŮŮŠŮ‚ Ř§Ů„Ř±Ů‚Ů…ŮŠ', "shortDesc": 'Ů‚Ů… Ř¨ŘŞŘ´ŘşŮŠŮ„ ŘĄŘąŮ„Ř§Ů†Ř§ŘŞ Ů…Ř±Ř¨Ř­Ř© ŮŘĄŘŻŘ§Ř±Ř© Ř§Ů„Ů†Ů…Ů Ů„Ů„Ř´Ř±ŮŘ§ŘŞ.', "fullDesc": 'ŘŞŘ­ŘŞŘ§Ř¬ ŮŮ„ Ř´Ř±ŮŘ© ŘĄŮ„Ů‰ Ř§Ů„Ů…Ř˛ŮŠŘŻ Ů…Ů† Ř§Ů„ŘąŮ…Ů„Ř§Řˇ. Ř§Ř¨ŘŻŘŁ ŮŮŘ§Ů„Ř© (SMMA) Ů„Ů…ŘłŘ§ŘąŘŻŘ© Ř§Ů„ŘąŮ„Ř§Ů…Ř§ŘŞ Ř§Ů„ŘŞŘ¬Ř§Ř±ŮŠŘ© ŘąŮ„Ů‰ Ř§Ů„Ů†Ů…Ů Ů…Ů† Ř®Ů„Ř§Ů„ ŘĄŘąŮ„Ř§Ů†Ř§ŘŞ ŮŮŠŘłŘ¨ŮŮŘŚ ŘŞŮŠŮ ŘŞŮŮŘŚ ŮŘ¬ŮŘ¬Ů„. Ř·Ů„Ř¨ Ů…Ř±ŘŞŮŘąŘŚ ŮŘ®ŘŻŮ…Ř© Ů‚Ř§Ř¨Ů„Ř© Ů„Ů„ŘŞŮŘłŘą.', "steps": [ { "title": 'Ř§ŘłŘŞŘ±Ř§ŘŞŮŠŘ¬ŮŠŘ© Ř§Ů„ŘĄŘąŮ„Ř§Ů†', "desc": 'ŘŞŘąŮ„Ů… ŘŞŘ´ŘşŮŠŮ„ Ř­Ů…Ů„Ř§ŘŞ Ů…Ř±Ř¨Ř­Ř©.' }, { "title": 'ŘŞŮ‚ŘŻŮŠŮ… Ř§Ů„Ř®ŘŻŮ…Ř©', "desc": 'ŮŮ„ŘŻ ŘąŮ…Ů„Ř§Řˇ Ů…Ř­ŘŞŮ…Ů„ŮŠŮ† Ů„Ů„ŘąŮ…Ů„Ř§Řˇ.' }, { "title": 'Ů†Ů…Ů Ř§Ů„ŮŮŘ§Ů„Ř©', "desc": 'Ř§Ř¨Ů† ŮŘ±ŮŠŮ‚Ů‹Ř§ Ů„Ů„ŘąŮ…Ů„ Ř§Ů„Ů…ŮŹŘ±Ř¶ŮŠ.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Ř§Ů„ŘŞŘŻŘ§ŮŮ„ Ř§Ů„Ů…Ř§Ů„ŮŠ', "shortDesc": 'Ř­Ů„Ů„ Ř§Ů„ŘŁŘłŮŘ§Ů‚ ŮŘŞŘŻŘ§ŮŮ„ Ř§Ů„ŘąŮ…Ů„Ř§ŘŞ Ř§Ů„Ů…Ř´ŮŘ±Ř©ŘŚ Ř§Ů„ŮŮŘ±ŮŘłŘŚ ŘŁŮ Ř§Ů„Ů…Ř¤Ř´Ř±Ř§ŘŞ.', "fullDesc": 'ŘŁŘŞŮ‚Ů† Ů…ŮŘ§Ů‡ŮŠŮ… Ř§Ů„ŘŞŘ­Ů„ŮŠŮ„ Ř§Ů„ŮŮ†ŮŠ Ř§Ů„Ř±Ř¦ŮŠŘłŮŠŘ© Ů„Ů„ŘŞŮ†Ů‚Ů„ ŮŮŠ Ř§Ů„ŘŁŘłŮŘ§Ů‚ Ř§Ů„Ů…Ř§Ů„ŮŠŘ©. ŘŞŘąŮ„Ů… ŘĄŘŻŘ§Ř±Ř© Ř§Ů„Ů…Ř®Ř§Ř·Ř±ŘŚ ŮŘąŮ„Ů… Ř§Ů„Ů†ŮŘłŘŚ ŮŘ§Ů„Ř§ŘłŘŞŘ±Ř§ŘŞŮŠŘ¬ŮŠŘ§ŘŞ Ů„Ů„Ř±Ř¨Ř­ Ů…Ů† ŘŞŘ­Ř±ŮŘ§ŘŞ Ř§Ů„ŘłŮŮ‚ Ř¨Ř´ŮŮ„ Ů…ŘłŘŞŮ‚Ů„.', "steps": [ { "title": 'Ř§Ů„ŘŞŘ­Ů„ŮŠŮ„', "desc": 'Ř§Ů‚Ř±ŘŁ Ř§Ů„Ř±ŘłŮŮ… Ř§Ů„Ř¨ŮŠŘ§Ů†ŮŠŘ© ŮŮ‡ŮŠŮŮ„ Ř§Ů„ŘłŮŮ‚.' }, { "title": 'ŘĄŘŻŘ§Ř±Ř© Ř§Ů„Ů…Ř®Ř§Ř·Ř±', "desc": 'Ř§Ř­Ů…Ů Ř±ŘŁŘł Ů…Ř§Ů„Ů ŘŁŮŮ„Ř§Ů‹.' }, { "title": 'Ř§Ů„ŘŞŮ†ŮŮŠŘ°', "desc": 'Ů†ŮŘ° ŘµŮŮ‚Ř§ŘŞ Ř°Ř§ŘŞ Ř§Ř­ŘŞŮ…Ř§Ů„ŮŠŘ© ŘąŘ§Ů„ŮŠŘ©.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'ŘµŮ†Ř§ŘąŘ© Ř§Ů„Ů…Ř­ŘŞŮŮ‰', "shortDesc": 'Ř§Ř¨Ů† ŘąŮ„Ř§Ů…Ř© ŘŞŘ¬Ř§Ř±ŮŠŘ© Ř´Ř®ŘµŮŠŘ© ŮŘ­Ů‚Ů‚ Ř§Ů„ŘŻŘ®Ů„ Ů…Ů† Ř¬Ů…Ů‡ŮŘ±Ů.', "fullDesc": 'Ř§Ů„Ř§Ů†ŘŞŘ¨Ř§Ů‡ Ů‡Ů Ř§Ů„ŘąŮ…Ů„Ř© Ř§Ů„Ř¬ŘŻŮŠŘŻŘ©. ŘŞŘąŮ„Ů… ŮŮŠŮŮŠŘ© ŘĄŮ†Ř´Ř§Řˇ Ů…Ř­ŘŞŮŮ‰ ŮŮŠŘ±ŮŘłŮŠ Ů‚ŘµŮŠŘ±ŘŚ ŮŘ¨Ů†Ř§Řˇ Ů…ŘŞŘ§Ř¨ŘąŮŠŮ† Ů…Ř®Ů„ŘµŮŠŮ†ŘŚ ŮŘŞŘ­Ů‚ŮŠŮ‚ Ř§Ů„ŘŻŘ®Ů„ Ů…Ů† Ř®Ů„Ř§Ů„ Ř§Ů„Ř±ŘąŘ§ŮŠŘ©ŘŚ ŘŁŮ Ř§Ů„ŘŞŘłŮŮŠŮ‚ Ř¨Ř§Ů„ŘąŮ…ŮŮ„Ř©ŘŚ ŘŁŮ Ů…Ů†ŘŞŘ¬Ř§ŘŞŮ Ř§Ů„Ř®Ř§ŘµŘ©.', "steps": [ { "title": 'Ů†ŘµŮŘµ ŮŮŠŘ±ŮŘłŮŠŘ©', "desc": 'Ř§Ř¬Ř°Ř¨ Ř§Ů„Ů…Ř´Ř§Ů‡ŘŻŮŠŮ† ŮŮŘ±Ů‹Ř§.' }, { "title": 'Ř§Ů„ŘĄŮ†ŘŞŘ§Ř¬', "desc": 'ŘµŮŘ± ŮŘ­Ř±Ř± Ů…Ů‚Ř§Ř·Řą ŘąŘ§Ů„ŮŠŘ© Ř§Ů„Ř¬ŮŘŻŘ©.' }, { "title": 'ŘŞŘ­Ů‚ŮŠŮ‚ Ř§Ů„ŘŻŘ®Ů„', "desc": 'Ř­ŮŮ„ Ř§Ů„Ů…Ř´Ř§Ů‡ŘŻŘ§ŘŞ ŘĄŮ„Ů‰ ŘŻŘ®Ů„.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'Ř§Ů„ŘŞŘ¬Ř§Ř±Ř© Ř§Ů„ŘĄŮ„ŮŘŞŘ±ŮŮ†ŮŠŘ©', "shortDesc": 'Ř¨Řą Ů…Ů†ŘŞŘ¬Ř§ŘŞ Ů…Ř§ŘŻŮŠŘ© ŘąŘ§Ů„Ů…ŮŠŮ‹Ř§ ŘŻŮŮ† Ř§Ů„Ř§Ř­ŘŞŮŘ§Ř¸ Ř¨Ů…Ř®Ř˛ŮŮ†.', "fullDesc": 'Ř§Ř¨ŘŻŘŁ Ů…ŘŞŘ¬Ř± ŘŻŘ±ŮŘ¨Ř´ŮŠŘ¨ŮŠŮ†Řş ŘŁŮ ŘąŮ„Ř§Ů…Ř© ŘŞŘ¬Ř§Ř±ŮŠŘ©. ŘŞŘąŮ„Ů… Ř§Ů„Ř¨Ř­Ř« ŘąŮ† Ř§Ů„Ů…Ů†ŘŞŘ¬Ř§ŘŞŘŚ ŮŘąŮ„Ř§Ů‚Ř§ŘŞ Ř§Ů„Ů…ŮŘ±ŘŻŮŠŮ†ŘŚ ŮŮŮŠŮŮŠŘ© Ř¨Ů†Ř§Řˇ ŮŘ§Ř¬Ů‡Ř© Ů…ŘŞŘ¬Ř± Ů…Ř­ŮŮ„Ř© ŘąŮ„Ů‰ Ř´ŮŘ¨ŮŠŮŘ§ŮŠ.', "steps": [ { "title": 'ŘµŮŠŘŻ Ř§Ů„Ů…Ů†ŘŞŘ¬Ř§ŘŞ', "desc": 'Ř¬ŘŻ Ů…Ů†ŘŞŘ¬Ř§ŘŞ Ř±Ř§Ř¨Ř­Ř©.' }, { "title": 'Ř¨Ů†Ř§Řˇ Ř§Ů„Ů…ŘŞŘ¬Ř±', "desc": 'ŘµŮ…Ů… Ů…ŮŮ‚ŘąŮ‹Ř§ ŘąŘ§Ů„ŮŠ Ř§Ů„ŘŞŘ­ŮŮŠŮ„.' }, { "title": 'Ř§Ů„ŘĄŘ·Ů„Ř§Ů‚', "desc": 'ŮŘ¬Ů‡ Ř§Ů„Ř˛ŮŠŘ§Ř±Ř§ŘŞ ŮŮ†ŮŘ° Ř§Ů„Ř·Ů„Ř¨Ř§ŘŞ.' } ] }
    ],
    "be": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS Bouwer', "shortDesc": 'CreĂ«er en schaal softwareproducten die terugkerende inkomsten genereren.', "fullDesc": 'Software as a Service (SaaS) is de gouden standaard voor digitaal inkomen. Leer marktlacunes te identificeren, te bouwen met no-code of code tools, en een abonnementsbedrijf op te schalen.', "steps": [ { "title": 'Ideevorming', "desc": 'Vind winstgevende problemen om op te lossen.' }, { "title": 'MVP Bouw', "desc": 'Lanceer snel een werkend prototype.' }, { "title": 'Schalen', "desc": 'Verkrijg gebruikers en terugkerende inkomsten.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Beheers de kunst van overtuiging om alles met woorden te verkopen.', "fullDesc": 'Goede teksten maken miljoenen. Leer de psychologie achter overtuiging, hoe je landingspagina\'s, e-mails en advertenties schrijft die vreemden omzetten in klanten voor hoge tarieven.', "steps": [ { "title": 'Psychologie', "desc": 'Begrijp wat actie aandrijft.' }, { "title": 'Kaders', "desc": 'Beheers bewezen schrijfstructuren.' }, { "title": 'Klantenwerving', "desc": 'Haal goedbetaalde opdrachten binnen.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Digitale Marketing', "shortDesc": 'Draai winstgevende advertenties en beheer groei voor bedrijven.', "fullDesc": 'Elk bedrijf heeft meer klanten nodig. Start een bureau (SMMA) dat merken helpt groeien via Facebook Ads, TikTok Ads en Google Ads. Veel vraag, schaalbare service.', "steps": [ { "title": 'Advertentiestrategie', "desc": 'Leer winstgevende campagnes te draaien.' }, { "title": 'Dienstverlening', "desc": 'Genereer leads voor klanten.' }, { "title": 'Bureau Groei', "desc": 'Bouw een team voor vervullend werk.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'FinanciĂ«le Handel', "shortDesc": 'Analyseer markten en verhandel Crypto, Forex of Indexen.', "fullDesc": 'Beheers belangrijke technische analyseconcepten om financiĂ«le markten te navigeren. Leer risicobeheer, psychologie en strategieĂ«n om zelfstandig te profiteren van marktbewegingen.', "steps": [ { "title": 'Analyse', "desc": 'Lees grafieken en marktstructuur.' }, { "title": 'Risicobeheer', "desc": 'Bescherm eerst je kapitaal.' }, { "title": 'Uitvoering', "desc": 'Plaats transacties met hoge waarschijnlijkheid.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Content Creatie', "shortDesc": 'Bouw een persoonlijk merk en verdien aan je publiek.', "fullDesc": 'Aandacht is de nieuwe valuta. Leer hoe je virale short-form content maakt, een trouwe aanhang opbouwt en verdient via sponsoring, affiliates of je eigen producten.', "steps": [ { "title": 'Virale Scripts', "desc": 'Grijp kijkers direct.' }, { "title": 'Productie', "desc": 'Film en edit clips van hoge kwaliteit.' }, { "title": 'Monetarisatie', "desc": 'Zet views om in inkomen.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Verkoop fysieke producten wereldwijd zonder voorraad.', "fullDesc": 'Start een dropshipping of eigen merk webshop. Leer productonderzoek, leveranciersrelaties en hoe je een converterende winkel opbouwt op Shopify.', "steps": [ { "title": 'Product Jacht', "desc": 'Vind winnende producten.' }, { "title": 'Winkel Bouw', "desc": 'Ontwerp een site met hoge conversie.' }, { "title": 'Lancering', "desc": 'Drijf verkeer en vervul bestellingen.' } ] }
    ],
    "bs": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS Graditelj', "shortDesc": 'Kreiraj i skaliraj softverske proizvode koji donose ponavljajuÄ‡e prihode.', "fullDesc": 'Software as a Service (SaaS) je zlatni standard digitalnog prihoda. NauÄŤi kako prepoznati trĹľiĹˇne praznine, graditi koristeÄ‡i no-code ili kod alate, i skalirati pretplatniÄŤki biznis.', "steps": [ { "title": 'Ideacija', "desc": 'PronaÄ‘i profitabilne probleme za rjeĹˇavanje.' }, { "title": 'MVP Izrada', "desc": 'Brzo lansiraj funkcionalan prototip.' }, { "title": 'Skaliranje', "desc": 'Stekni korisnike i ponavljajuÄ‡e prihode.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Savladaj umjetnost uvjeravanja da prodaĹˇ bilo Ĺˇta rijeÄŤima.', "fullDesc": 'Dobar tekst donosi milione. NauÄŤi psihologiju iza uvjeravanja, kako pisati landing stranice, emailove i oglase koji pretvaraju strance u kupce za visoke honorare.', "steps": [ { "title": 'Psihologija', "desc": 'Razumi Ĺˇta pokreÄ‡e akciju.' }, { "title": 'Okviri', "desc": 'Savladaj dokazane strukture pisanja.' }, { "title": 'Akvizicija Klijenata', "desc": 'Osiguraj visoko plaÄ‡ene ugovore.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Digitalni Marketing', "shortDesc": 'Vodi profitabilne oglase i upravljaj rastom za biznise.', "fullDesc": 'Svaki biznis treba viĹˇe kupaca. Pokreni agenciju (SMMA) pomaĹľuÄ‡i brendovima da rastu kroz Facebook Ads, TikTok Ads i Google Ads. Velika potraĹľnja, skalabilna usluga.', "steps": [ { "title": 'Strategija Oglasa', "desc": 'NauÄŤi voditi profitabilne kampanje.' }, { "title": 'Isporuka Usluge', "desc": 'GeneriĹˇi lidove za klijente.' }, { "title": 'Rast Agencije', "desc": 'Izgradi tim za ispunjavajuÄ‡i rad.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Finansijsko Trgovanje', "shortDesc": 'Analiziraj trĹľiĹˇta i trguj Kripto, Forex ili Indeksima.', "fullDesc": 'Savladaj kljuÄŤne koncepte tehniÄŤke analize za navigaciju finansijskim trĹľiĹˇtima. NauÄŤi upravljanje rizikom, psihologiju i strategije da profitiraĹˇ od trĹľiĹˇnih kretanja samostalno.', "steps": [ { "title": 'Analiza', "desc": 'ÄŚitaj grafikone i strukturu trĹľiĹˇta.' }, { "title": 'Upravljanje Rizikom', "desc": 'Prvo zaĹˇtiti svoj kapital.' }, { "title": 'IzvrĹˇenje', "desc": 'Postavljaj trgovine visoke vjerovatnoÄ‡e.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Kreiranje SadrĹľaja', "shortDesc": 'Izgradi liÄŤni brend i monetizuj svoju publiku.', "fullDesc": 'PaĹľnja je nova valuta. NauÄŤi kako kreirati viralni kratki sadrĹľaj, izgraditi lojalne pratioce i zaraditi kroz sponzorstva, partnere ili vlastite proizvode.', "steps": [ { "title": 'Viralni Skripti', "desc": 'Odmah privuci gledaoce.' }, { "title": 'Produkcija', "desc": 'Snimaj i montiraj klipove visokog kvaliteta.' }, { "title": 'Monetizacija', "desc": 'Pretvori preglede u prihod.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Prodaji fiziÄŤke proizvode globalno bez drĹľanja zaliha.', "fullDesc": 'Pokreni dropshipping ili brendiranu web trgovinu. NauÄŤi istraĹľivanje proizvoda, odnose s dobavljaÄŤima i kako izgraditi konvertujuÄ‡u trgovinu na Shopify-u.', "steps": [ { "title": 'Potraga za Proizvodima', "desc": 'PronaÄ‘i pobjedniÄŤke proizvode.' }, { "title": 'Izrada Trgovine', "desc": 'Dizajniraj stranicu s visokom konverzijom.' }, { "title": 'Lansiranje', "desc": 'Dovedi saobraÄ‡aj i ispuni narudĹľbe.' } ] }
    ],
    "zh": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS ćž„ĺ»şč€…', "shortDesc": 'ĺ›ĺ»şĺą¶ć‰©ĺ±•äş§ç”źç»Źĺ¸¸ć€§ć”¶ĺ…Ąçš„č˝Żä»¶äş§ĺ“ă€‚', "fullDesc": 'č˝Żä»¶ĺŤłćśŤĺŠˇ (SaaS) ćŻć•°ĺ­—ć”¶ĺ…Ąçš„é»„é‡‘ć ‡ĺ‡†ă€‚ĺ­¦äą ĺ¦‚ä˝•čŻ†ĺ«ĺ¸‚ĺśşç©şç™˝ďĽŚä˝żç”¨ć— ä»Łç ć–ä»Łç ĺ·Ąĺ…·ćž„ĺ»şďĽŚĺą¶ć‰©ĺ±•ĺźşäşŽč®˘é…çš„ä¸šĺŠˇă€‚', "steps": [ { "title": 'ćž„ć€ť', "desc": 'ć‰ľĺ°ćś‰ĺ©ĺŹŻĺ›ľçš„é—®é˘ćťĄč§Łĺ†łă€‚' }, { "title": 'MVP ćž„ĺ»ş', "desc": 'ĺż«é€źćŽ¨ĺ‡şĺŹŻç”¨çš„ĺŽźĺž‹ă€‚' }, { "title": 'ć‰©ĺ±•', "desc": 'čŽ·ĺŹ–ç”¨ć·ĺ’Śç»Źĺ¸¸ć€§ć”¶ĺ…Ąă€‚' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'ć–‡ćˇĺ†™ä˝ś', "shortDesc": 'ćŽŚćŹˇčŻ´ćśŤçš„č‰şćśŻďĽŚç”¨ć–‡ĺ­—é”€ĺ”®ä»»ä˝•ä¸śčĄżă€‚', "fullDesc": 'ĺĄ˝çš„ć–‡ćˇč˝ĺ›é€ ć•°ç™ľä¸‡ä»·ĺ€Ľă€‚ĺ­¦äą čŻ´ćśŤčŚĺŽçš„ĺżç†ĺ­¦ďĽŚĺ¦‚ä˝•ć’°ĺ†™çť€é™†éˇµă€ç”µĺ­é‚®ä»¶ĺ’Śĺążĺ‘ŠďĽŚĺ°†é™Śç”źäşşč˝¬ĺŚ–ä¸şé«ä»č´ąĺ®˘ć·ă€‚', "steps": [ { "title": 'ĺżç†ĺ­¦', "desc": 'äş†č§Łé©±ĺŠ¨čˇŚĺŠ¨çš„ĺ› ç´ ă€‚' }, { "title": 'ćˇ†ćž¶', "desc": 'ćŽŚćŹˇç»Źčż‡éŞŚčŻçš„ĺ†™ä˝śç»“ćž„ă€‚' }, { "title": 'ĺ®˘ć·čŽ·ĺŹ–', "desc": 'čŽ·ĺľ—é«č–Şé•żćśźĺĺŚă€‚' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'ć•°ĺ­—čĄé”€', "shortDesc": 'ä¸şäĽä¸ščżčĄç›ĺ©ĺążĺ‘Šĺą¶ç®ˇç†ĺ˘žé•żă€‚', "fullDesc": 'ćŻŹä¸ŞäĽä¸šé˝éś€č¦ć›´ĺ¤šĺ®˘ć·ă€‚é€ščż‡ Facebook ĺążĺ‘Šă€TikTok ĺążĺ‘Šĺ’Ś Google ĺążĺ‘Šĺ¸®ĺŠ©ĺ“ç‰Śĺ˘žé•żďĽŚĺ›ĺŠžä¸€ĺ®¶ä»Łç†ćśşćž„ (SMMA)ă€‚éś€ć±‚é‡Źĺ¤§ďĽŚćśŤĺŠˇĺŹŻć‰©ĺ±•ă€‚', "steps": [ { "title": 'ĺążĺ‘Šç­–ç•Ą', "desc": 'ĺ­¦äą čżčĄç›ĺ©çš„ć´»ĺŠ¨ă€‚' }, { "title": 'ćśŤĺŠˇäş¤ä»', "desc": 'ä¸şĺ®˘ć·ç”źćć˝śĺś¨ĺ®˘ć·ă€‚' }, { "title": 'ä»Łç†ćśşćž„ĺ˘žé•ż', "desc": 'ĺ»şç«‹ĺ›˘éźä»Ąĺ®Śćĺ·Ąä˝śă€‚' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'é‡‘čžŤäş¤ć“', "shortDesc": 'ĺ†ćžĺ¸‚ĺśşĺą¶äş¤ć“ĺŠ ĺŻ†č´§ĺ¸ă€ĺ¤–ć±‡ć–ćŚ‡ć•°ă€‚', "fullDesc": 'ćŽŚćŹˇĺ…łé”®çš„ćŠ€ćśŻĺ†ćžć¦‚ĺżµä»Ąé©ľé©­é‡‘čžŤĺ¸‚ĺśşă€‚ĺ­¦äą éŁŽé™©ç®ˇç†ă€ĺżç†ĺ­¦ĺ’Śç­–ç•ĄďĽŚä»Ąç‹¬ç«‹ä»Žĺ¸‚ĺśşćł˘ĺŠ¨ä¸­čŽ·ĺ©ă€‚', "steps": [ { "title": 'ĺ†ćž', "desc": 'é…čŻ»ĺ›ľčˇ¨ĺ’Śĺ¸‚ĺśşç»“ćž„ă€‚' }, { "title": 'éŁŽé™©ç®ˇç†', "desc": 'é¦–ĺ…äżťćŠ¤ä˝ çš„čµ„ćś¬ă€‚' }, { "title": 'ć‰§čˇŚ', "desc": 'čż›čˇŚé«ć¦‚çŽ‡äş¤ć“ă€‚' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'ĺ†…ĺ®ąĺ›ä˝ś', "shortDesc": 'ĺ»şç«‹ä¸Şäşşĺ“ç‰Śĺą¶ä»ŽĺŹ—äĽ—ä¸­čŽ·ĺ©ă€‚', "fullDesc": 'ćł¨ć„ŹĺŠ›ćŻć–°çš„č´§ĺ¸ă€‚ĺ­¦äą ĺ¦‚ä˝•ĺ›ä˝śç—…ćŻ’ĺĽŹçź­č§†é˘‘ĺ†…ĺ®ąďĽŚĺ»şç«‹ĺż ĺ®žçš„čż˝éšŹč€…ďĽŚĺą¶é€ščż‡čµžĺŠ©ă€č”ç›źć–č‡Şĺ·±çš„äş§ĺ“čŽ·ĺ©ă€‚', "steps": [ { "title": 'ç—…ćŻ’č„ščŚ', "desc": 'ç«‹ĺŤłĺ¸ĺĽ•č§‚äĽ—ă€‚' }, { "title": 'ĺ¶ä˝ś', "desc": 'ć‹Ťć‘„ĺ’Śĺ‰Şčľ‘é«č´¨é‡Źç‰‡ć®µă€‚' }, { "title": 'ĺŹçŽ°', "desc": 'ĺ°†č§‚çś‹č˝¬ĺŚ–ä¸şć”¶ĺ…Ąă€‚' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'ç”µĺ­ĺ•†ĺŠˇ', "shortDesc": 'ĺś¨ĺ…¨çčŚĺ›´ĺ†…é”€ĺ”®ĺ®žä˝“äş§ĺ“ďĽŚć— éś€ćŚćś‰ĺş“ĺ­ă€‚', "fullDesc": 'ĺĽ€č®ľä¸€ĺ®¶ä»ŁĺŹ‘č´§ć–ĺ“ç‰Śç”µĺ­ĺ•†ĺŠˇĺ•†ĺş—ă€‚ĺ­¦äą äş§ĺ“ç ”ç©¶ă€äľ›ĺş”ĺ•†ĺ…łçł»ďĽŚä»ĄĺŹŠĺ¦‚ä˝•ĺś¨ Shopify ä¸Šĺ»şç«‹é«č˝¬ĺŚ–çŽ‡çš„ĺş—éť˘ă€‚', "steps": [ { "title": 'äş§ĺ“ćśĺŻ»', "desc": 'ć‰ľĺ°čŽ·čśäş§ĺ“ă€‚' }, { "title": 'ĺ•†ĺş—ćž„ĺ»ş', "desc": 'č®ľč®ˇé«č˝¬ĺŚ–çŽ‡ç˝‘ç«™ă€‚' }, { "title": 'ĺŹ‘ĺ¸', "desc": 'é©±ĺŠ¨ćµé‡Źĺą¶ĺ±ĄčˇŚč®˘ĺŤ•ă€‚' } ] }
    ],
    "hr": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS Graditelj', "shortDesc": 'Kreiraj i skaliraj softverske proizvode koji donose ponavljajuÄ‡e prihode.', "fullDesc": 'Software as a Service (SaaS) je zlatni standard digitalnog prihoda. NauÄŤi kako prepoznati trĹľiĹˇne praznine, graditi koristeÄ‡i no-code ili kod alate, i skalirati pretplatniÄŤki biznis.', "steps": [ { "title": 'Ideacija', "desc": 'PronaÄ‘i profitabilne probleme za rjeĹˇavanje.' }, { "title": 'MVP Izrada', "desc": 'Brzo lansiraj funkcionalan prototip.' }, { "title": 'Skaliranje', "desc": 'Stekni korisnike i ponavljajuÄ‡e prihode.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Savladaj umjetnost uvjeravanja da prodaĹˇ bilo Ĺˇto rijeÄŤima.', "fullDesc": 'Dobar tekst donosi milijune. NauÄŤi psihologiju iza uvjeravanja, kako pisati landing stranice, emailove i oglase koji pretvaraju strance u kupce za visoke honorare.', "steps": [ { "title": 'Psihologija', "desc": 'Razumi Ĺˇto pokreÄ‡e akciju.' }, { "title": 'Okviri', "desc": 'Savladaj dokazane strukture pisanja.' }, { "title": 'Akvizicija Klijenata', "desc": 'Osiguraj visoko plaÄ‡ene ugovore.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Digitalni Marketing', "shortDesc": 'Vodi profitabilne oglase i upravljaj rastom za biznise.', "fullDesc": 'Svaki biznis treba viĹˇe kupaca. Pokreni agenciju (SMMA) pomaĹľuÄ‡i brendovima da rastu kroz Facebook Ads, TikTok Ads i Google Ads. Velika potraĹľnja, skalabilna usluga.', "steps": [ { "title": 'Strategija Oglasa', "desc": 'NauÄŤi voditi profitabilne kampanje.' }, { "title": 'Isporuka Usluge', "desc": 'Generiraj leadove za klijente.' }, { "title": 'Rast Agencije', "desc": 'Izgradi tim za ispunjavajuÄ‡i rad.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Financijsko Trgovanje', "shortDesc": 'Analiziraj trĹľiĹˇta i trguj Kripto, Forex ili Indeksima.', "fullDesc": 'Savladaj kljuÄŤne koncepte tehniÄŤke analize za navigaciju financijskim trĹľiĹˇtima. NauÄŤi upravljanje rizikom, psihologiju i strategije da profitiraĹˇ od trĹľiĹˇnih kretanja samostalno.', "steps": [ { "title": 'Analiza', "desc": 'ÄŚitaj grafikone i strukturu trĹľiĹˇta.' }, { "title": 'Upravljanje Rizikom', "desc": 'Prvo zaĹˇtiti svoj kapital.' }, { "title": 'IzvrĹˇenje', "desc": 'Postavljaj trgovine visoke vjerojatnosti.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Kreiranje SadrĹľaja', "shortDesc": 'Izgradi osobni brend i monetiziraj svoju publiku.', "fullDesc": 'PaĹľnja je nova valuta. NauÄŤi kako kreirati viralni kratki sadrĹľaj, izgraditi lojalne pratitelje i zaraditi kroz sponzorstva, partnere ili vlastite proizvode.', "steps": [ { "title": 'Viralni Skripti', "desc": 'Odmah privuci gledatelje.' }, { "title": 'Produkcija', "desc": 'Snimaj i montiraj klipove visoke kvalitete.' }, { "title": 'Monetizacija', "desc": 'Pretvori preglede u prihod.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Prodaji fiziÄŤke proizvode globalno bez drĹľanja zaliha.', "fullDesc": 'Pokreni dropshipping ili brendiranu web trgovinu. NauÄŤi istraĹľivanje proizvoda, odnose s dobavljaÄŤima i kako izgraditi konvertirajuÄ‡u trgovinu na Shopify-u.', "steps": [ { "title": 'Potraga za Proizvodima', "desc": 'PronaÄ‘i pobjedniÄŤke proizvode.' }, { "title": 'Izrada Trgovine', "desc": 'Dizajniraj stranicu s visokom konverzijom.' }, { "title": 'Lansiranje', "desc": 'Dovedi promet i ispuni narudĹľbe.' } ] }
    ],
    "cs": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS TvĹŻrce', "shortDesc": 'VytvĂˇĹ™ejte a ĹˇkĂˇlujte softwarovĂ© produkty generujĂ­cĂ­ opakovanĂ© pĹ™Ă­jmy.', "fullDesc": 'Software as a Service (SaaS) je zlatĂ˝ standard digitĂˇlnĂ­ho pĹ™Ă­jmu. NauÄŤte se identifikovat mezery na trhu, budovat pomocĂ­ no-code nebo kĂłdovacĂ­ch nĂˇstrojĹŻ a ĹˇkĂˇlovat pĹ™edplatitelskĂ© podnikĂˇnĂ­.', "steps": [ { "title": 'NĂˇpad', "desc": 'NajdÄ›te ziskovĂ© problĂ©my k Ĺ™eĹˇenĂ­.' }, { "title": 'Tvorba MVP', "desc": 'Rychle spusĹĄte funkÄŤnĂ­ prototyp.' }, { "title": 'Ĺ kĂˇlovĂˇnĂ­', "desc": 'ZĂ­skejte uĹľivatele a opakovanĂ© pĹ™Ă­jmy.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'OvlĂˇdnÄ›te umÄ›nĂ­ pĹ™esvÄ›dÄŤovĂˇnĂ­ a prodĂˇvejte cokoliv slovy.', "fullDesc": 'DobrĂ˝ text vydÄ›lĂˇvĂˇ miliony. Poznejte psychologii pĹ™esvÄ›dÄŤovĂˇnĂ­, jak psĂˇt vstupnĂ­ strĂˇnky, e-maily a reklamy, kterĂ© mÄ›nĂ­ cizince v zĂˇkaznĂ­ky za vysokĂ© poplatky.', "steps": [ { "title": 'Psychologie', "desc": 'Pochopte, co pohĂˇnĂ­ akci.' }, { "title": 'RĂˇmce', "desc": 'OvlĂˇdnÄ›te osvÄ›dÄŤenĂ© struktury psanĂ­.' }, { "title": 'ZĂ­skĂˇvĂˇnĂ­ klientĹŻ', "desc": 'ZĂ­skejte vysoce placenĂ© zakĂˇzky.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'DigitĂˇlnĂ­ Marketing', "shortDesc": 'Spravujte ziskovĂ© reklamy a Ĺ™iÄŹte rĹŻst firem.', "fullDesc": 'KaĹľdĂˇ firma potĹ™ebuje vĂ­ce zĂˇkaznĂ­kĹŻ. ZaloĹľte agenturu (SMMA) pomĂˇhajĂ­cĂ­ znaÄŤkĂˇm rĹŻst prostĹ™ednictvĂ­m Facebook Ads, TikTok Ads a Google Ads. VysokĂˇ poptĂˇvka, ĹˇkĂˇlovatelnĂˇ sluĹľba.', "steps": [ { "title": 'ReklamnĂ­ strategie', "desc": 'NauÄŤte se Ĺ™Ă­dit ziskovĂ© kampanÄ›.' }, { "title": 'PoskytovĂˇnĂ­ sluĹľeb', "desc": 'Generujte leady pro klientĹŻ.' }, { "title": 'RĹŻst agentury', "desc": 'Vybudujte tĂ˝m pro naplĹujĂ­cĂ­ prĂˇci.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'FinanÄŤnĂ­ ObchodovĂˇnĂ­', "shortDesc": 'Analyzujte trhy a obchodujte Krypto, Forex nebo Indexy.', "fullDesc": 'OvlĂˇdnÄ›te klĂ­ÄŤovĂ© koncepty technickĂ© analĂ˝zy pro navigaci na finanÄŤnĂ­ch trzĂ­ch. NauÄŤte se Ĺ™Ă­zenĂ­ rizik, psychologii a strategie, jak nezĂˇvisle profitovat z trĹľnĂ­ch pohybĹŻ.', "steps": [ { "title": 'AnalĂ˝za', "desc": 'ÄŚtÄ›te grafy a strukturu trhu.' }, { "title": 'ĹĂ­zenĂ­ rizik', "desc": 'Nejprve chraĹte svĹŻj kapitĂˇl.' }, { "title": 'Exekuce', "desc": 'ProvĂˇdÄ›jte obchody s vysokou pravdÄ›podobnostĂ­.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Tvorba Obsahu', "shortDesc": 'Vybudujte osobnĂ­ znaÄŤku a monetizujte svĂ© publikum.', "fullDesc": 'Pozornost je novĂˇ mÄ›na. NauÄŤte se vytvĂˇĹ™et virĂˇlnĂ­ krĂˇtkĂˇ videa, budovat vÄ›rnĂ© sledujĂ­cĂ­ a vydÄ›lĂˇvat prostĹ™ednictvĂ­m sponzorstvĂ­, affiliate nebo vlastnĂ­ch produktĹŻ.', "steps": [ { "title": 'VirĂˇlnĂ­ scĂ©nĂˇĹ™e', "desc": 'OkamĹľitÄ› zaujmÄ›te divĂˇky.' }, { "title": 'Produkce', "desc": 'NatĂˇÄŤejte a stĹ™Ă­hejte kvalitnĂ­ klipy.' }, { "title": 'Monetizace', "desc": 'PromÄ›Ĺte zhlĂ©dnutĂ­ v pĹ™Ă­jem.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'ProdĂˇvejte fyzickĂ© produkty globĂˇlnÄ› bez drĹľenĂ­ zĂˇsob.', "fullDesc": 'SpusĹĄte dropshippingovĂ˝ nebo znaÄŤkovĂ˝ e-shop. NauÄŤte se prĹŻzkum produktĹŻ, vztahy s dodavateli a jak vybudovat konverznĂ­ obchod na Shopify.', "steps": [ { "title": 'HledĂˇnĂ­ produktĹŻ', "desc": 'NajdÄ›te vĂ­tÄ›znĂ© produkty.' }, { "title": 'Stavba obchodu', "desc": 'NavrhnÄ›te web s vysokou konverzĂ­.' }, { "title": 'SpuĹˇtÄ›nĂ­', "desc": 'PĹ™iveÄŹte nĂˇvĹˇtevnost a vyĹ™izujte objednĂˇvky.' } ] }
    ],

    "nl": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS Bouwer', "shortDesc": 'CreĂ«er en schaal softwareproducten die terugkerende inkomsten genereren.', "fullDesc": 'Software as a Service (SaaS) is de gouden standaard voor digitaal inkomen. Leer marktlacunes te identificeren, te bouwen met no-code of code tools, en een abonnementsbedrijf op te schalen.', "steps": [ { "title": 'Ideevorming', "desc": 'Vind winstgevende problemen om op te lossen.' }, { "title": 'MVP Bouw', "desc": 'Lanceer snel een werkend prototype.' }, { "title": 'Schalen', "desc": 'Verkrijg gebruikers en terugkerende inkomsten.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Beheers de kunst van overtuiging om alles met woorden te verkopen.', "fullDesc": 'Goede teksten maken miljoenen. Leer de psychologie achter overtuiging, hoe je landingspagina\'s, e-mails en advertenties schrijft die vreemden omzetten in klanten voor hoge tarieven.', "steps": [ { "title": 'Psychologie', "desc": 'Begrijp wat actie aandrijft.' }, { "title": 'Kaders', "desc": 'Beheers bewezen schrijfstructuren.' }, { "title": 'Klantenwerving', "desc": 'Haal goedbetaalde opdrachten binnen.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Digitale Marketing', "shortDesc": 'Draai winstgevende advertenties en beheer groei voor bedrijven.', "fullDesc": 'Elk bedrijf heeft meer klanten nodig. Start een bureau (SMMA) dat merken helpt groeien via Facebook Ads, TikTok Ads en Google Ads. Veel vraag, schaalbare service.', "steps": [ { "title": 'Advertentiestrategie', "desc": 'Leer winstgevende campagnes te draaien.' }, { "title": 'Dienstverlening', "desc": 'Genereer leads voor klanten.' }, { "title": 'Bureau Groei', "desc": 'Bouw een team voor vervullend werk.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'FinanciĂ«le Handel', "shortDesc": 'Analyseer markten en verhandel Crypto, Forex of Indexen.', "fullDesc": 'Beheers belangrijke technische analyseconcepten om financiĂ«le markten te navigeren. Leer risicobeheer, psychologie en strategieĂ«n om zelfstandig te profiteren van marktbewegingen.', "steps": [ { "title": 'Analyse', "desc": 'Lees grafieken en marktstructuur.' }, { "title": 'Risicobeheer', "desc": 'Bescherm eerst je kapitaal.' }, { "title": 'Uitvoering', "desc": 'Plaats transacties met hoge waarschijnlijkheid.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Content Creatie', "shortDesc": 'Bouw een persoonlijk merk en verdien aan je publiek.', "fullDesc": 'Aandacht is de nieuwe valuta. Leer hoe je virale short-form content maakt, een trouwe aanhang opbouwt en verdient via sponsoring, affiliates of je eigen producten.', "steps": [ { "title": 'Virale Scripts', "desc": 'Grijp kijkers direct.' }, { "title": 'Productie', "desc": 'Film en edit clips van hoge kwaliteit.' }, { "title": 'Monetarisatie', "desc": 'Zet views om in inkomen.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Verkoop fysieke producten wereldwijd zonder voorraad.', "fullDesc": 'Start een dropshipping of eigen merk webshop. Leer productonderzoek, leveranciersrelaties en hoe je een converterende winkel opbouwt op Shopify.', "steps": [ { "title": 'Product Jacht', "desc": 'Vind winnende producten.' }, { "title": 'Winkel Bouw', "desc": 'Ontwerp een site met hoge conversie.' }, { "title": 'Lancering', "desc": 'Drijf verkeer en vervul bestellingen.' } ] }
    ],
    "fr": [
        { "id": 'saas', "icon": 'đź’»', "title": 'CrĂ©ateur SaaS', "shortDesc": 'CrĂ©ez et dĂ©veloppez des logiciels gĂ©nĂ©rant des revenus rĂ©currents.', "fullDesc": 'Le Software as a Service (SaaS) est la rĂ©fĂ©rence en matiĂ¨re de revenus numĂ©riques. Apprenez Ă  identifier les besoins, Ă  construire avec ou sans code, et Ă  faire croĂ®tre une activitĂ© par abonnement.', "steps": [ { "title": 'IdĂ©ation', "desc": 'Trouvez des problĂ¨mes rentables Ă  rĂ©soudre.' }, { "title": 'CrĂ©ation MVP', "desc": 'Lancez rapidement un prototype fonctionnel.' }, { "title": 'Croissance', "desc": 'AcquĂ©rez des utilisateurs et des revenus rĂ©currents.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'MaĂ®trisez l\'art de la persuasion pour tout vendre avec des mots.', "fullDesc": 'Un bon texte rapporte des millions. Apprenez la psychologie de la persuasion, comment rĂ©diger des pages de vente, des emails et des publicitĂ©s qui convertissent les inconnus en clients.', "steps": [ { "title": 'Psychologie', "desc": 'Comprenez ce qui pousse Ă  l\'action.' }, { "title": 'Structures', "desc": 'MaĂ®trisez les structures d\'Ă©criture Ă©prouvĂ©es.' }, { "title": 'Clients', "desc": 'DĂ©crochez des contrats bien rĂ©munĂ©rĂ©s.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Marketing Digital', "shortDesc": 'GĂ©rez des publicitĂ©s rentables et la croissance des entreprises.', "fullDesc": 'Toute entreprise a besoin de plus de clients. Lancez une agence (SMMA) aidant les marques Ă  croĂ®tre via Facebook Ads, TikTok Ads et Google Ads. Forte demande, service Ă©volutif.', "steps": [ { "title": 'StratĂ©gie', "desc": 'Apprenez Ă  gĂ©rer des campagnes rentables.' }, { "title": 'Prestation', "desc": 'GĂ©nĂ©rez des leads pour les clients.' }, { "title": 'Agence', "desc": 'Construisez une Ă©quipe pour le travail.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Trading Financier', "shortDesc": 'Analysez les marchĂ©s et tradez Crypto, Forex ou Indices.', "fullDesc": 'MaĂ®trisez l\'analyse technique pour naviguer sur les marchĂ©s financiers. Apprenez la gestion des risques, la psychologie et les stratĂ©gies pour profiter des mouvements du marchĂ©.', "steps": [ { "title": 'Analyse', "desc": 'Lisez les graphiques et la structure du marchĂ©.' }, { "title": 'Risque', "desc": 'ProtĂ©gez d\'abord votre capital.' }, { "title": 'ExĂ©cution', "desc": 'Placez des trades Ă  haute probabilitĂ©.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'CrĂ©ation de Contenu', "shortDesc": 'BĂ˘tissez une marque personnelle et monĂ©tisez votre audience.', "fullDesc": 'L\'attention est la nouvelle monnaie. Apprenez Ă  crĂ©er du contenu viral court, Ă  bĂ˘tir une audience fidĂ¨le et Ă  gagner via le sponsoring, l\'affiliation ou vos propres produits.', "steps": [ { "title": 'Scripts Viraux', "desc": 'Accrochez les spectateurs instantanĂ©ment.' }, { "title": 'Production', "desc": 'Filmez et montez des clips de qualitĂ©.' }, { "title": 'MonĂ©tisation', "desc": 'Transformez les vues en revenus.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Vendez des produits physiques mondialement sans stock.', "fullDesc": 'Lancez une boutique dropshipping ou une marque. Apprenez la recherche de produits, les relations fournisseurs et comment bĂ˘tir une boutique Shopify qui convertit.', "steps": [ { "title": 'Recherche', "desc": 'Trouvez des produits gagnants.' }, { "title": 'Boutique', "desc": 'Concevez un site Ă  haute conversion.' }, { "title": 'Lancement', "desc": 'Attirez du trafic et expĂ©diez les commandes.' } ] }
    ],
    "de": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS GrĂĽnder', "shortDesc": 'Erstelle und skaliere Softwareprodukte mit wiederkehrenden Einnahmen.', "fullDesc": 'Software as a Service (SaaS) ist der Goldstandard fĂĽr digitales Einkommen. Lerne MarktlĂĽcken zu finden, mit No-Code oder Code zu bauen und ein Abo-GeschĂ¤ft zu skalieren.', "steps": [ { "title": 'Ideenfindung', "desc": 'Finde profitable Probleme.' }, { "title": 'MVP Bau', "desc": 'Starte schnell einen funktionierenden Prototyp.' }, { "title": 'Skalierung', "desc": 'Gewinne Nutzer und wiederkehrende Einnahmen.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Meistere die Kunst der Ăśberzeugung, um alles mit Worten zu verkaufen.', "fullDesc": 'Gute Texte machen Millionen. Lerne die Psychologie der Ăśberzeugung, wie man Landing Pages, E-Mails und Anzeigen schreibt, die Fremde in Kunden verwandeln.', "steps": [ { "title": 'Psychologie', "desc": 'Verstehe, was Handlungen auslĂ¶st.' }, { "title": 'Frameworks', "desc": 'Meistere bewĂ¤hrte Schreibstrukturen.' }, { "title": 'Kundengewinnung', "desc": 'Erhalte hochbezahlte AuftrĂ¤ge.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Digitales Marketing', "shortDesc": 'Schalte profitable Anzeigen und manage Wachstum fĂĽr Firmen.', "fullDesc": 'Jedes Unternehmen braucht mehr Kunden. Starte eine Agentur (SMMA), die Marken hilft, durch Facebook Ads, TikTok Ads und Google Ads zu wachsen. Hohe Nachfrage, skalierbar.', "steps": [ { "title": 'Anzeigenstrategie', "desc": 'Lerne profitable Kampagnen zu schalten.' }, { "title": 'Dienstleistung', "desc": 'Generiere Leads fĂĽr Kunden.' }, { "title": 'Agenturwachstum', "desc": 'Baue ein Team fĂĽr die Arbeit auf.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Finanzhandel', "shortDesc": 'Analysiere MĂ¤rkte und handle Krypto, Forex oder Indizes.', "fullDesc": 'Meistere technische Analyse, um FinanzmĂ¤rkte zu navigieren. Lerne Risikomanagement, Psychologie und Strategien, um unabhĂ¤ngig von Marktbewegungen zu profitieren.', "steps": [ { "title": 'Analyse', "desc": 'Lese Charts und Marktstruktur.' }, { "title": 'Risikomanagement', "desc": 'SchĂĽtze zuerst dein Kapital.' }, { "title": 'AusfĂĽhrung', "desc": 'Platziere Trades mit hoher Wahrscheinlichkeit.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Content Creation', "shortDesc": 'Baue eine Personal Brand und monetarisiere dein Publikum.', "fullDesc": 'Aufmerksamkeit ist die neue WĂ¤hrung. Lerne, virale Kurzvideos zu erstellen, eine treue Followerschaft aufzubauen und durch Sponsoring, Affiliates oder eigene Produkte zu verdienen.', "steps": [ { "title": 'Virale Skripte', "desc": 'Fessle Zuschauer sofort.' }, { "title": 'Produktion', "desc": 'Filme und schneide hochwertige Clips.' }, { "title": 'Monetarisierung', "desc": 'Verwandle Views in Einkommen.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-Commerce', "shortDesc": 'Verkaufe physische Produkte weltweit ohne Lagerbestand.', "fullDesc": 'Starte einen Dropshipping- oder Marken-Shop. Lerne Produktrecherche, Lieferantenbeziehungen und wie man einen konvertierenden Store auf Shopify baut.', "steps": [ { "title": 'Produktsuche', "desc": 'Finde Gewinnerprodukte.' }, { "title": 'Shop-Bau', "desc": 'Design eine High-Conversion-Seite.' }, { "title": 'Launch', "desc": 'Generiere Traffic und erfĂĽlle Bestellungen.' } ] }
    ],
    "mk": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS Đ“Ń€Đ°Đ´Đ¸Ń‚ĐµĐ»', "shortDesc": 'ĐšŃ€ĐµĐ¸Ń€Đ°ŃŃ‚Đµ Đ¸ ŃĐşĐ°Đ»Đ¸Ń€Đ°ŃŃ‚Đµ ŃĐľŃ„Ń‚Đ˛ĐµŃ€ŃĐşĐ¸ ĐżŃ€ĐľĐ¸Đ·Đ˛ĐľĐ´Đ¸ ŃĐľ ĐżĐľĐ˛Ń‚ĐľŃ€Đ»Đ¸Đ˛Đ¸ ĐżŃ€Đ¸Ń…ĐľĐ´Đ¸.', "fullDesc": 'ĐˇĐľŃ„Ń‚Đ˛ĐµŃ€ĐľŃ‚ ĐşĐ°ĐşĐľ ŃŃĐ»ŃĐłĐ° (SaaS) Đµ Đ·Đ»Đ°Ń‚Đ˝Đ¸ĐľŃ‚ ŃŃ‚Đ°Đ˝Đ´Đ°Ń€Đ´ Đ·Đ° Đ´Đ¸ĐłĐ¸Ń‚Đ°Đ»ĐµĐ˝ ĐżŃ€Đ¸Ń…ĐľĐ´. ĐťĐ°ŃŃ‡ĐµŃ‚Đµ ĐşĐ°ĐşĐľ Đ´Đ° Đ¸Đ´ĐµĐ˝Ń‚Đ¸Ń„Đ¸ĐşŃĐ˛Đ°Ń‚Đµ ĐżŃ€Đ°Đ·Đ˝Đ¸Đ˝Đ¸ Đ˝Đ° ĐżĐ°Đ·Đ°Ń€ĐľŃ‚, Đ´Đ° ĐłŃ€Đ°Đ´Đ¸Ń‚Đµ ŃĐľ no-code Đ¸Đ»Đ¸ ĐşĐľĐ´ Đ°Đ»Đ°Ń‚ĐşĐ¸ Đ¸ Đ´Đ° ŃĐşĐ°Đ»Đ¸Ń€Đ°Ń‚Đµ Đ±Đ¸Đ·Đ˝Đ¸Ń ŃĐľ ĐżŃ€ĐµŃ‚ĐżĐ»Đ°Ń‚Đ°.', "steps": [ { "title": 'ĐĐ´ĐµŃĐ°', "desc": 'ĐťĐ°ŃĐ´ĐµŃ‚Đµ ĐżŃ€ĐľŃ„Đ¸Ń‚Đ°Đ±Đ¸Đ»Đ˝Đ¸ ĐżŃ€ĐľĐ±Đ»ĐµĐĽĐ¸ Đ·Đ° Ń€ĐµŃĐ°Đ˛Đ°ŃšĐµ.' }, { "title": 'MVP ĐĐ·Ń€Đ°Đ±ĐľŃ‚ĐşĐ°', "desc": 'Đ‘Ń€Đ·Đľ Đ»Đ°Đ˝ŃĐ¸Ń€Đ°ŃŃ‚Đµ Ń„ŃĐ˝ĐşŃ†Đ¸ĐľĐ˝Đ°Đ»ĐµĐ˝ ĐżŃ€ĐľŃ‚ĐľŃ‚Đ¸Đż.' }, { "title": 'ĐˇĐşĐ°Đ»Đ¸Ń€Đ°ŃšĐµ', "desc": 'ĐˇŃ‚ĐµĐşĐ˝ĐµŃ‚Đµ ĐşĐľŃ€Đ¸ŃĐ˝Đ¸Ń†Đ¸ Đ¸ ĐżĐľĐ˛Ń‚ĐľŃ€Đ»Đ¸Đ˛Đ¸ ĐżŃ€Đ¸Ń…ĐľĐ´Đ¸.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'ĐˇĐľĐ˛Đ»Đ°Đ´Đ°ŃŃ‚Đµ ŃĐ° ŃĐĽĐµŃ‚Đ˝ĐľŃŃ‚Đ° Đ˝Đ° ŃĐ±ĐµĐ´ŃĐ˛Đ°ŃšĐµ Đ·Đ° Đ´Đ° ĐżŃ€ĐľĐ´Đ°Đ´ĐµŃ‚Đµ Đ±Đ¸Đ»Đľ ŃŃ‚Đľ ŃĐľ Đ·Đ±ĐľŃ€ĐľĐ˛Đ¸.', "fullDesc": 'Đ”ĐľĐ±Đ°Ń€ Ń‚ĐµĐşŃŃ‚ Đ˝ĐľŃĐ¸ ĐĽĐ¸Đ»Đ¸ĐľĐ˝Đ¸. ĐťĐ°ŃŃ‡ĐµŃ‚Đµ ŃĐ° ĐżŃĐ¸Ń…ĐľĐ»ĐľĐłĐ¸ŃĐ°Ń‚Đ° Đ·Đ°Đ´ ŃĐ±ĐµĐ´ŃĐ˛Đ°ŃšĐµŃ‚Đľ, ĐşĐ°ĐşĐľ Đ´Đ° ĐżĐ¸ŃŃĐ˛Đ°Ń‚Đµ Ń†ĐµĐ»Đ˝Đ¸ ŃŃ‚Ń€Đ°Đ˝Đ¸Ń†Đ¸, Đµ-ĐżĐľŃŃ‚Đ° Đ¸ Ń€ĐµĐşĐ»Đ°ĐĽĐ¸ ĐşĐľĐ¸ ĐłĐ¸ ĐżŃ€ĐµŃ‚Đ˛ĐľŃ€Đ°Đ°Ń‚ ŃŃ‚Ń€Đ°Đ˝Ń†Đ¸Ń‚Đµ Đ˛Đľ ĐşĐ»Đ¸ĐµĐ˝Ń‚Đ¸.', "steps": [ { "title": 'ĐźŃĐ¸Ń…ĐľĐ»ĐľĐłĐ¸ŃĐ°', "desc": 'Đ Đ°Đ·Đ±ĐµŃ€ĐµŃ‚Đµ ŃŃ‚Đľ ŃĐ° ĐżĐľŃ‚Ń‚Đ¸ĐşĐ˝ŃĐ˛Đ° Đ°ĐşŃ†Đ¸ŃĐ°Ń‚Đ°.' }, { "title": 'Đ Đ°ĐĽĐşĐ¸', "desc": 'ĐˇĐľĐ˛Đ»Đ°Đ´Đ°ŃŃ‚Đµ Đ´ĐľĐşĐ°Đ¶Đ°Đ˝Đ¸ ŃŃ‚Ń€ŃĐşŃ‚ŃŃ€Đ¸ Đ˝Đ° ĐżĐ¸ŃŃĐ˛Đ°ŃšĐµ.' }, { "title": 'ĐšĐ»Đ¸ĐµĐ˝Ń‚Đ¸', "desc": 'ĐžĐ±ĐµĐ·Đ±ĐµĐ´ĐµŃ‚Đµ Đ˛Đ¸ŃĐľĐşĐľ ĐżĐ»Đ°Ń‚ĐµĐ˝Đ¸ Đ´ĐľĐłĐľĐ˛ĐľŃ€Đ¸.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Đ”Đ¸ĐłĐ¸Ń‚Đ°Đ»ĐµĐ˝ ĐśĐ°Ń€ĐşĐµŃ‚Đ¸Đ˝Đł', "shortDesc": 'Đ’ĐľĐ´ĐµŃ‚Đµ ĐżŃ€ĐľŃ„Đ¸Ń‚Đ°Đ±Đ¸Đ»Đ˝Đ¸ Ń€ĐµĐşĐ»Đ°ĐĽĐ¸ Đ¸ ŃĐżŃ€Đ°Đ˛ŃĐ˛Đ°ŃŃ‚Đµ ŃĐľ Ń€Đ°ŃŃ‚ĐľŃ‚ Đ·Đ° Đ±Đ¸Đ·Đ˝Đ¸ŃĐ¸.', "fullDesc": 'ĐˇĐµĐşĐľŃ Đ±Đ¸Đ·Đ˝Đ¸Ń Đ¸ĐĽĐ° ĐżĐľŃ‚Ń€ĐµĐ±Đ° ĐľĐ´ ĐżĐľĐ˛ĐµŃśĐµ ĐşĐ»Đ¸ĐµĐ˝Ń‚Đ¸. Đ—Đ°ĐżĐľŃ‡Đ˝ĐµŃ‚Đµ Đ°ĐłĐµĐ˝Ń†Đ¸ŃĐ° (SMMA) ĐżĐľĐĽĐ°ĐłĐ°ŃŃśĐ¸ Đ¸ĐĽ Đ˝Đ° Đ±Ń€ĐµĐ˝Đ´ĐľĐ˛Đ¸Ń‚Đµ Đ´Đ° Ń€Đ°ŃŃ‚Đ°Ń‚ ĐżŃ€ĐµĐşŃ Facebook Ads, TikTok Ads Đ¸ Google Ads. Đ“ĐľĐ»ĐµĐĽĐ° ĐżĐľĐ±Đ°Ń€ŃĐ˛Đ°Ń‡ĐşĐ°, ŃĐşĐ°Đ»Đ°Đ±Đ¸Đ»Đ˝Đ° ŃŃĐ»ŃĐłĐ°.', "steps": [ { "title": 'ĐˇŃ‚Ń€Đ°Ń‚ĐµĐłĐ¸ŃĐ°', "desc": 'ĐťĐ°ŃŃ‡ĐµŃ‚Đµ Đ´Đ° Đ˛ĐľĐ´Đ¸Ń‚Đµ ĐżŃ€ĐľŃ„Đ¸Ń‚Đ°Đ±Đ¸Đ»Đ˝Đ¸ ĐşĐ°ĐĽĐżĐ°ŃšĐ¸.' }, { "title": 'ĐŃĐżĐľŃ€Đ°ĐşĐ°', "desc": 'Đ“ĐµĐ˝ĐµŃ€Đ¸Ń€Đ°ŃŃ‚Đµ ĐżĐľŃ‚ĐµĐ˝Ń†Đ¸ŃĐ°Đ»Đ˝Đ¸ ĐşĐ»Đ¸ĐµĐ˝Ń‚Đ¸.' }, { "title": 'Đ Đ°ŃŃ‚ Đ˝Đ° ĐĐłĐµĐ˝Ń†Đ¸ŃĐ°', "desc": 'ĐĐ·ĐłŃ€Đ°Đ´ĐµŃ‚Đµ Ń‚Đ¸ĐĽ Đ·Đ° Đ¸ŃĐżĐľĐ»Đ˝Đ¸Ń‚ĐµĐ»Đ˝Đ° Ń€Đ°Đ±ĐľŃ‚Đ°.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Đ¤Đ¸Đ˝Đ°Đ˝ŃĐ¸ŃĐşĐľ Đ˘Ń€ĐłŃĐ˛Đ°ŃšĐµ', "shortDesc": 'ĐĐ˝Đ°Đ»Đ¸Đ·Đ¸Ń€Đ°ŃŃ‚Đµ ĐżĐ°Đ·Đ°Ń€Đ¸ Đ¸ Ń‚Ń€ĐłŃĐ˛Đ°ŃŃ‚Đµ ĐšŃ€Đ¸ĐżŃ‚Đľ, Đ¤ĐľŃ€ĐµĐşŃ Đ¸Đ»Đ¸ ĐĐ˝Đ´ĐµĐşŃĐ¸.', "fullDesc": 'ĐˇĐľĐ˛Đ»Đ°Đ´Đ°ŃŃ‚Đµ ĐłĐ¸ ĐşĐ»ŃŃ‡Đ˝Đ¸Ń‚Đµ ĐşĐľĐ˝Ń†ĐµĐżŃ‚Đ¸ Đ˝Đ° Ń‚ĐµŃ…Đ˝Đ¸Ń‡ĐşĐ° Đ°Đ˝Đ°Đ»Đ¸Đ·Đ°. ĐťĐ°ŃŃ‡ĐµŃ‚Đµ ŃĐżŃ€Đ°Đ˛ŃĐ˛Đ°ŃšĐµ ŃĐľ Ń€Đ¸Đ·Đ¸Đş, ĐżŃĐ¸Ń…ĐľĐ»ĐľĐłĐ¸ŃĐ° Đ¸ ŃŃ‚Ń€Đ°Ń‚ĐµĐłĐ¸Đ¸ Đ·Đ° ŃĐ°ĐĽĐľŃŃ‚ĐľŃĐ˝Đľ ĐżŃ€ĐľŃ„Đ¸Ń‚Đ¸Ń€Đ°ŃšĐµ ĐľĐ´ ĐżĐ°Đ·Đ°Ń€Đ˝Đ¸Ń‚Đµ Đ´Đ˛Đ¸Đ¶ĐµŃšĐ°.', "steps": [ { "title": 'ĐĐ˝Đ°Đ»Đ¸Đ·Đ°', "desc": 'Đ§Đ¸Ń‚Đ°ŃŃ‚Đµ ĐłŃ€Đ°Ń„Đ¸ĐşĐľĐ˝Đ¸ Đ¸ ĐżĐ°Đ·Đ°Ń€Đ˝Đ° ŃŃ‚Ń€ŃĐşŃ‚ŃŃ€Đ°.' }, { "title": 'Đ Đ¸Đ·Đ¸Đş', "desc": 'ĐźŃ€Đ˛Đľ Đ·Đ°ŃŃ‚Đ¸Ń‚ĐµŃ‚Đµ ĐłĐľ ŃĐ˛ĐľŃĐľŃ‚ ĐşĐ°ĐżĐ¸Ń‚Đ°Đ».' }, { "title": 'ĐĐ·Đ˛Ń€ŃŃĐ˛Đ°ŃšĐµ', "desc": 'ĐźĐľŃŃ‚Đ°Đ˛ŃĐ˛Đ°ŃŃ‚Đµ Ń‚Ń€ĐłĐľĐ˛Đ¸Đ¸ ŃĐľ Đ˛Đ¸ŃĐľĐşĐ° Đ˛ĐµŃ€ĐľŃĐ°Ń‚Đ˝ĐľŃŃ‚.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'ĐšŃ€ĐµĐ¸Ń€Đ°ŃšĐµ ĐˇĐľĐ´Ń€Đ¶Đ¸Đ˝Đ°', "shortDesc": 'ĐĐ·ĐłŃ€Đ°Đ´ĐµŃ‚Đµ Đ»Đ¸Ń‡ĐµĐ˝ Đ±Ń€ĐµĐ˝Đ´ Đ¸ ĐĽĐľĐ˝ĐµŃ‚Đ¸Đ·Đ¸Ń€Đ°ŃŃ‚Đµ ŃĐ° ŃĐ˛ĐľŃĐ°Ń‚Đ° ĐżŃĐ±Đ»Đ¸ĐşĐ°.', "fullDesc": 'Đ’Đ˝Đ¸ĐĽĐ°Đ˝Đ¸ĐµŃ‚Đľ Đµ Đ˝ĐľĐ˛Đ°Ń‚Đ° Đ˛Đ°Đ»ŃŃ‚Đ°. ĐťĐ°ŃŃ‡ĐµŃ‚Đµ ĐşĐ°ĐşĐľ Đ´Đ° ĐşŃ€ĐµĐ¸Ń€Đ°Ń‚Đµ Đ˛Đ¸Ń€Đ°Đ»Đ˝Đ° ĐşŃ€Đ°Ń‚ĐşĐ° ŃĐľĐ´Ń€Đ¶Đ¸Đ˝Đ°, Đ´Đ° Đ¸Đ·ĐłŃ€Đ°Đ´Đ¸Ń‚Đµ Đ»ĐľŃĐ°Đ»Đ˝Đ¸ ŃĐ»ĐµĐ´Đ±ĐµĐ˝Đ¸Ń†Đ¸ Đ¸ Đ´Đ° Đ·Đ°Ń€Đ°Đ±ĐľŃ‚Đ¸Ń‚Đµ ĐżŃ€ĐµĐşŃ ŃĐżĐľĐ˝Đ·ĐľŃ€ŃŃ‚Đ˛Đ° Đ¸Đ»Đ¸ ŃĐľĐżŃŃ‚Đ˛ĐµĐ˝Đ¸ ĐżŃ€ĐľĐ¸Đ·Đ˛ĐľĐ´Đ¸.', "steps": [ { "title": 'Đ’Đ¸Ń€Đ°Đ»Đ˝Đ¸ ĐˇŃ†ĐµĐ˝Đ°Ń€Đ¸ŃĐ°', "desc": 'Đ’ĐµĐ´Đ˝Đ°Ń ĐżŃ€Đ¸Đ˛Đ»ĐµŃ‡ĐµŃ‚Đµ ĐłĐ»ĐµĐ´Đ°Ń‡Đ¸.' }, { "title": 'ĐźŃ€ĐľĐ´ŃĐşŃ†Đ¸ŃĐ°', "desc": 'ĐˇĐ˝Đ¸ĐĽĐ°ŃŃ‚Đµ Đ¸ ĐĽĐľĐ˝Ń‚Đ¸Ń€Đ°ŃŃ‚Đµ ĐşĐ˛Đ°Đ»Đ¸Ń‚ĐµŃ‚Đ˝Đ¸ ĐşĐ»Đ¸ĐżĐľĐ˛Đ¸.' }, { "title": 'ĐśĐľĐ˝ĐµŃ‚Đ¸Đ·Đ°Ń†Đ¸ŃĐ°', "desc": 'ĐźŃ€ĐµŃ‚Đ˛ĐľŃ€ĐµŃ‚Đµ ĐłĐ¸ ĐżŃ€ĐµĐłĐ»ĐµĐ´Đ¸Ń‚Đµ Đ˛Đľ ĐżŃ€Đ¸Ń…ĐľĐ´.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'ĐźŃ€ĐľĐ´Đ°Đ˛Đ°ŃŃ‚Đµ Ń„Đ¸Đ·Đ¸Ń‡ĐşĐ¸ ĐżŃ€ĐľĐ¸Đ·Đ˛ĐľĐ´Đ¸ ĐłĐ»ĐľĐ±Đ°Đ»Đ˝Đľ Đ±ĐµĐ· Đ·Đ°Đ»Đ¸Ń…Đ°.', "fullDesc": 'Đ—Đ°ĐżĐľŃ‡Đ˝ĐµŃ‚Đµ dropshipping Đ¸Đ»Đ¸ Đ±Ń€ĐµĐ˝Đ´Đ¸Ń€Đ°Đ˝Đ° ĐżŃ€ĐľĐ´Đ°Đ˛Đ˝Đ¸Ń†Đ°. ĐťĐ°ŃŃ‡ĐµŃ‚Đµ Đ¸ŃŃ‚Ń€Đ°Đ¶ŃĐ˛Đ°ŃšĐµ Đ˝Đ° ĐżŃ€ĐľĐ¸Đ·Đ˛ĐľĐ´Đ¸ Đ¸ ĐşĐ°ĐşĐľ Đ´Đ° Đ¸Đ·ĐłŃ€Đ°Đ´Đ¸Ń‚Đµ ĐżŃ€ĐľĐ´Đ°Đ˛Đ˝Đ¸Ń†Đ° Đ˝Đ° Shopify ŃŃ‚Đľ ĐşĐľĐ˝Đ˛ĐµŃ€Ń‚Đ¸Ń€Đ°.', "steps": [ { "title": 'ĐźĐľŃ‚Ń€Đ°ĐłĐ° ĐżĐľ ĐźŃ€ĐľĐ¸Đ·Đ˛ĐľĐ´Đ¸', "desc": 'ĐťĐ°ŃĐ´ĐµŃ‚Đµ ĐżĐľĐ±ĐµĐ´Đ˝Đ¸Ń‡ĐşĐ¸ ĐżŃ€ĐľĐ¸Đ·Đ˛ĐľĐ´Đ¸.' }, { "title": 'ĐĐ·Ń€Đ°Đ±ĐľŃ‚ĐşĐ° Đ˝Đ° ĐźŃ€ĐľĐ´Đ°Đ˛Đ˝Đ¸Ń†Đ°', "desc": 'Đ”Đ¸Đ·Đ°ŃĐ˝Đ¸Ń€Đ°ŃŃ‚Đµ ŃĐ°ŃŃ‚ ŃĐľ Đ˛Đ¸ŃĐľĐşĐ° ĐşĐľĐ˝Đ˛ĐµŃ€Đ·Đ¸ŃĐ°.' }, { "title": 'Đ›Đ°Đ˝ŃĐ¸Ń€Đ°ŃšĐµ', "desc": 'Đ”ĐľĐ˝ĐµŃĐµŃ‚Đµ ŃĐľĐľĐ±Ń€Đ°ŃśĐ°Ń Đ¸ Đ¸ŃĐżĐľĐ»Đ˝ĐµŃ‚Đµ Đ˝Đ°Ń€Đ°Ń‡ĐşĐ¸.' } ] }
    ],
    "mt": [
        { "id": 'saas', "icon": 'đź’»', "title": 'Bennej SaaS', "shortDesc": 'OÄ§loq u skala prodotti tas-software li jiÄˇÄˇeneraw dÄ§ul rikorrenti.', "fullDesc": 'Software as a Service (SaaS) huwa l-istandard tad-deheb tad-dÄ§ul diÄˇitali. TgÄ§allem kif tidentifika lakuni fis-suq, tibni bl-uĹĽu ta\' gÄ§odod no-code jew kodiÄ‹i, u tiskala negozju bbaĹĽat fuq abbonament.', "steps": [ { "title": 'Ideazzjoni', "desc": 'Sib problemi profittabbli biex issolvi.' }, { "title": 'Bini MVP', "desc": 'Niedi prototip li jaÄ§dem malajr.' }, { "title": 'Skala', "desc": 'Akkwista utenti u dÄ§ul rikorrenti.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Ikkontrolla l-arti tal-perswaĹĽjoni biex tbigÄ§ xi Ä§aÄˇa bil-kliem.', "fullDesc": 'Kopja tajba tagÄ§mel miljuni. TgÄ§allem il-psikoloÄˇija wara l-perswaĹĽjoni, kif tikteb landing pages, emails, u reklami li jikkonvertu barranin fi klijenti gÄ§al tariffi gÄ§oljin.', "steps": [ { "title": 'PsikoloÄˇija', "desc": 'Ifhem x\'imexxi l-azzjoni.' }, { "title": 'Oqfsa', "desc": 'Ikkontrolla strutturi ta\' kitba ppruvati.' }, { "title": 'Akkwist ta\' Klijenti', "desc": 'Assigura kuntratti bi Ä§las gÄ§oli.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Marketing DiÄˇitali', "shortDesc": 'Mexxi reklami profittabbli u mmaniÄˇÄˇja t-tkabbir gÄ§an-negozji.', "fullDesc": 'Kull negozju jeÄ§tieÄˇ aktar klijenti. Ibda aÄˇenzija (SMMA) tgÄ§in lill-marki jikbru permezz ta\' Facebook Ads, TikTok Ads u Google Ads. Domanda gÄ§olja, servizz skalabbli.', "steps": [ { "title": 'StrateÄˇija tar-Reklami', "desc": 'TgÄ§allem tmexxi kampanji profittabbli.' }, { "title": 'Twassil tas-Servizz', "desc": 'IÄˇÄˇenera leads gÄ§all-klijenti.' }, { "title": 'Tkabbir tal-AÄˇenzija', "desc": 'Ibni tim gÄ§al xogÄ§ol sodisfaÄ‹enti.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'KummerÄ‹ Finanzjarju', "shortDesc": 'Analizza s-swieq u nnegozja Kripto, Forex jew IndiÄ‹i.', "fullDesc": 'Ikkontrolla kunÄ‹etti ewlenin ta\' analiĹĽi teknika biex tinnaviga fis-swieq finanzjarji. TgÄ§allem Äˇestjoni tar-riskju, psikoloÄˇija u strateÄˇiji biex tagÄ§mel profitt mill-movimenti tas-suq b\'mod indipendenti.', "steps": [ { "title": 'AnaliĹĽi', "desc": 'Aqra charts u struttura tas-suq.' }, { "title": 'Ä estjoni tar-Riskju', "desc": 'IpproteÄˇi l-kapital tiegÄ§ek l-ewwel.' }, { "title": 'EĹĽekuzzjoni', "desc": 'PoÄˇÄˇi kummerÄ‹ bi probabbiltĂ  gÄ§olja.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Ä¦olqien ta\' Kontenut', "shortDesc": 'Ibni marka personali u monetizza l-udjenza tiegÄ§ek.', "fullDesc": 'L-attenzjoni hija l-munita l-Äˇdida. TgÄ§allem kif toÄ§loq kontenut virali f\'forma qasira, tibni segwaÄ‹i leali u taqla\' permezz ta\' sponsorships, affiljati jew prodotti tiegÄ§ek stess.', "steps": [ { "title": 'Skripts Virali', "desc": 'IÄˇbed lit-telespettaturi istantanjament.' }, { "title": 'Produzzjoni', "desc": 'Iffilmja u editja klipps ta\' kwalitĂ  gÄ§olja.' }, { "title": 'Monetizzazzjoni', "desc": 'Dawwar il-views fi dÄ§ul.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'BiegÄ§ prodotti fiĹĽiÄ‹i globalment mingÄ§ajr ma ĹĽĹĽomm inventarju.', "fullDesc": 'Ibda Ä§anut dropshipping jew tad-ditta. TgÄ§allem ir-riÄ‹erka tal-prodott, ir-relazzjonijiet mal-fornituri u kif tibni vetrina li tikkonverti fuq Shopify.', "steps": [ { "title": 'KaÄ‹Ä‹a gÄ§all-Prodotti', "desc": 'Sib prodotti rebbieÄ§a.' }, { "title": 'Bini tal-Ä¦anut', "desc": 'Iddisinja sit b\'konverĹĽjoni gÄ§olja.' }, { "title": 'Tnedija', "desc": 'Mexxi traffiku u wettaq ordnijiet.' } ] }
    ],
    "me": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS Graditelj', "shortDesc": 'Kreiraj i skaliraj softverske proizvode koji donose ponavljajuÄ‡e prihode.', "fullDesc": 'Software as a Service (SaaS) je zlatni standard digitalnog prihoda. NauÄŤi kako prepoznati trĹľiĹˇne praznine, graditi koristeÄ‡i no-code ili kod alate, i skalirati pretplatniÄŤki biznis.', "steps": [ { "title": 'Ideacija', "desc": 'PronaÄ‘i profitabilne probleme za rjeĹˇavanje.' }, { "title": 'MVP Izrada', "desc": 'Brzo lansiraj funkcionalan prototip.' }, { "title": 'Skaliranje', "desc": 'Stekni korisnike i ponavljajuÄ‡e prihode.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Savladaj umjetnost uvjeravanja da prodaĹˇ bilo Ĺˇta rijeÄŤima.', "fullDesc": 'Dobar tekst donosi milione. NauÄŤi psihologiju iza uvjeravanja, kako pisati landing stranice, emailove i oglase koji pretvaraju strance u kupce za visoke honorare.', "steps": [ { "title": 'Psihologija', "desc": 'Razumi Ĺˇta pokreÄ‡e akciju.' }, { "title": 'Okviri', "desc": 'Savladaj dokazane strukture pisanja.' }, { "title": 'Akvizicija Klijenata', "desc": 'Osiguraj visoko plaÄ‡ene ugovore.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Digitalni Marketing', "shortDesc": 'Vodi profitabilne oglase i upravljaj rastom za biznise.', "fullDesc": 'Svaki biznis treba viĹˇe kupaca. Pokreni agenciju (SMMA) pomaĹľuÄ‡i brendovima da rastu kroz Facebook Ads, TikTok Ads i Google Ads. Velika potraĹľnja, skalabilna usluga.', "steps": [ { "title": 'Strategija Oglasa', "desc": 'NauÄŤi voditi profitabilne kampanje.' }, { "title": 'Isporuka Usluge', "desc": 'GeneriĹˇi lidove za klijente.' }, { "title": 'Rast Agencije', "desc": 'Izgradi tim za ispunjavajuÄ‡i rad.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Finansijsko Trgovanje', "shortDesc": 'Analiziraj trĹľiĹˇta i trguj Kripto, Forex ili Indeksima.', "fullDesc": 'Savladaj kljuÄŤne koncepte tehniÄŤke analize za navigaciju finansijskim trĹľiĹˇtima. NauÄŤi upravljanje rizikom, psihologiju i strategije da profitiraĹˇ od trĹľiĹˇnih kretanja samostalno.', "steps": [ { "title": 'Analiza', "desc": 'ÄŚitaj grafikone i strukturu trĹľiĹˇta.' }, { "title": 'Upravljanje Rizikom', "desc": 'Prvo zaĹˇtiti svoj kapital.' }, { "title": 'IzvrĹˇenje', "desc": 'Postavljaj trgovine visoke vjerovatnoÄ‡e.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Kreiranje SadrĹľaja', "shortDesc": 'Izgradi liÄŤni brend i monetizuj svoju publiku.', "fullDesc": 'PaĹľnja je nova valuta. NauÄŤi kako kreirati viralni kratki sadrĹľaj, izgraditi lojalne pratioce i zaraditi kroz sponzorstva, partnere ili vlastite proizvode.', "steps": [ { "title": 'Viralni Skripti', "desc": 'Odmah privuci gledaoce.' }, { "title": 'Produkcija', "desc": 'Snimaj i montiraj klipove visokog kvaliteta.' }, { "title": 'Monetizacija', "desc": 'Pretvori preglede u prihod.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Prodaji fiziÄŤke proizvode globalno bez drĹľanja zaliha.', "fullDesc": 'Pokreni dropshipping ili brendiranu web trgovinu. NauÄŤi istraĹľivanje proizvoda, odnose s dobavljaÄŤima i kako izgraditi konvertujuÄ‡u trgovinu na Shopify-u.', "steps": [ { "title": 'Potraga za Proizvodima', "desc": 'PronaÄ‘i pobjedniÄŤke proizvode.' }, { "title": 'Izrada Trgovine', "desc": 'Dizajniraj stranicu s visokom konverzijom.' }, { "title": 'Lansiranje', "desc": 'Dovedi saobraÄ‡aj i ispuni narudĹľbe.' } ] }
    ],
    "pt": [
        { "id": 'saas', "icon": 'đź’»', "title": 'Criador SaaS', "shortDesc": 'Crie e escale produtos de software que geram receita recorrente.', "fullDesc": 'Software como ServiĂ§o (SaaS) Ă© o padrĂŁo ouro da renda digital. Aprenda a identificar lacunas no mercado, construir usando ferramentas no-code ou cĂłdigo, e escalar um negĂłcio baseado em assinatura.', "steps": [ { "title": 'IdeaĂ§ĂŁo', "desc": 'Encontre problemas lucrativos para resolver.' }, { "title": 'ConstruĂ§ĂŁo MVP', "desc": 'Lance um protĂłtipo funcional rĂˇpido.' }, { "title": 'Escala', "desc": 'Adquira usuĂˇrios e receita recorrente.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Domine a arte da persuasĂŁo para vender qualquer coisa com palavras.', "fullDesc": 'Um bom texto faz milhĂµes. Aprenda a psicologia por trĂˇs da persuasĂŁo, como escrever landing pages, e-mails e anĂşncios que convertem estranhos em clientes por altas taxas.', "steps": [ { "title": 'Psicologia', "desc": 'Entenda o que impulsiona a aĂ§ĂŁo.' }, { "title": 'Estruturas', "desc": 'Domine estruturas de escrita comprovadas.' }, { "title": 'AquisiĂ§ĂŁo de Clientes', "desc": 'Garanta contratos bem pagos.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Marketing Digital', "shortDesc": 'Rode anĂşncios lucrativos e gerencie o crescimento para empresas.', "fullDesc": 'Toda empresa precisa de mais clientes. Inicie uma agĂŞncia (SMMA) ajudando marcas a crescer atravĂ©s de Facebook Ads, TikTok Ads e Google Ads. Alta demanda, serviĂ§o escalĂˇvel.', "steps": [ { "title": 'EstratĂ©gia de AnĂşncios', "desc": 'Aprenda a rodar campanhas lucrativas.' }, { "title": 'Entrega de ServiĂ§o', "desc": 'Gere leads para clientes.' }, { "title": 'Crescimento da AgĂŞncia', "desc": 'Construa uma equipe para trabalho gratificante.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Trading Financeiro', "shortDesc": 'Analise mercados e negocie Cripto, Forex ou ĂŤndices.', "fullDesc": 'Domine conceitos-chave de anĂˇlise tĂ©cnica para navegar nos mercados financeiros. Aprenda gestĂŁo de risco, psicologia e estratĂ©gias para lucrar com movimentos de mercado independentemente.', "steps": [ { "title": 'AnĂˇlise', "desc": 'Leia grĂˇficos e estrutura de mercado.' }, { "title": 'GestĂŁo de Risco', "desc": 'Proteja seu capital primeiro.' }, { "title": 'ExecuĂ§ĂŁo', "desc": 'Coloque ordens com alta probabilidade.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'CriaĂ§ĂŁo de ConteĂşdo', "shortDesc": 'Construa uma marca pessoal e monetize sua audiĂŞncia.', "fullDesc": 'AtenĂ§ĂŁo Ă© a nova moeda. Aprenda como criar conteĂşdo viral curto, construir seguidores leais e ganhar atravĂ©s de patrocĂ­nios, afiliados ou seus prĂłprios produtos.', "steps": [ { "title": 'Roteiros Virais', "desc": 'Prenda os espectadores instantaneamente.' }, { "title": 'ProduĂ§ĂŁo', "desc": 'Filme e edite clipes de alta qualidade.' }, { "title": 'MonetizaĂ§ĂŁo', "desc": 'Transforme visualizaĂ§Ăµes em renda.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Venda produtos fĂ­sicos globalmente sem manter estoque.', "fullDesc": 'Comece uma loja de dropshipping ou marca prĂłpria. Aprenda pesquisa de produtos, relaĂ§Ăµes com fornecedores e como construir uma vitrine que converte na Shopify.', "steps": [ { "title": 'CaĂ§a de Produtos', "desc": 'Encontre produtos vencedores.' }, { "title": 'ConstruĂ§ĂŁo da Loja', "desc": 'Desenhe um site de alta conversĂŁo.' }, { "title": 'LanĂ§amento', "desc": 'Direcione trĂˇfego e cumpra pedidos.' } ] }
    ],

    "ru": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS ĐˇĐľĐ·Đ´Đ°Ń‚ĐµĐ»ŃŚ', "shortDesc": 'ĐˇĐľĐ·Đ´Đ°Đ˛Đ°ĐąŃ‚Đµ Đ¸ ĐĽĐ°ŃŃŃ‚Đ°Đ±Đ¸Ń€ŃĐąŃ‚Đµ ĐżŃ€ĐľĐłŃ€Đ°ĐĽĐĽĐ˝Ń‹Đµ ĐżŃ€ĐľĐ´ŃĐşŃ‚Ń‹ Ń Ń€ĐµĐłŃĐ»ŃŹŃ€Đ˝Ń‹ĐĽ Đ´ĐľŃ…ĐľĐ´ĐľĐĽ.', "fullDesc": 'ĐźŃ€ĐľĐłŃ€Đ°ĐĽĐĽĐ˝ĐľĐµ ĐľĐ±ĐµŃĐżĐµŃ‡ĐµĐ˝Đ¸Đµ ĐşĐ°Đş ŃŃĐ»ŃĐłĐ° (SaaS) â€” ŃŤŃ‚Đľ Đ·ĐľĐ»ĐľŃ‚ĐľĐą ŃŃ‚Đ°Đ˝Đ´Đ°Ń€Ń‚ Ń†Đ¸Ń„Ń€ĐľĐ˛ĐľĐłĐľ Đ´ĐľŃ…ĐľĐ´Đ°. ĐŁĐ·Đ˝Đ°ĐąŃ‚Đµ, ĐşĐ°Đş Đ˝Đ°Ń…ĐľĐ´Đ¸Ń‚ŃŚ Ń€Ń‹Đ˝ĐľŃ‡Đ˝Ń‹Đµ Đ˝Đ¸ŃĐ¸, ŃĐľĐ·Đ´Đ°Đ˛Đ°Ń‚ŃŚ Ń ĐżĐľĐĽĐľŃ‰ŃŚŃŽ no-code Đ¸Đ»Đ¸ ĐşĐľĐ´Đ° Đ¸ ĐĽĐ°ŃŃŃ‚Đ°Đ±Đ¸Ń€ĐľĐ˛Đ°Ń‚ŃŚ Đ±Đ¸Đ·Đ˝ĐµŃ ĐżĐľ ĐżĐľĐ´ĐżĐ¸ŃĐşĐµ.', "steps": [ { "title": 'ĐĐ´ĐµŃŹ', "desc": 'ĐťĐ°ĐąĐ´Đ¸Ń‚Đµ ĐżŃ€Đ¸Đ±Ń‹Đ»ŃŚĐ˝Ń‹Đµ ĐżŃ€ĐľĐ±Đ»ĐµĐĽŃ‹ Đ´Đ»ŃŹ Ń€ĐµŃĐµĐ˝Đ¸ŃŹ.' }, { "title": 'ĐˇĐľĐ·Đ´Đ°Đ˝Đ¸Đµ MVP', "desc": 'Đ‘Ń‹ŃŃ‚Ń€Đľ Đ·Đ°ĐżŃŃŃ‚Đ¸Ń‚Đµ Ń€Đ°Đ±ĐľŃ‚Đ°ŃŽŃ‰Đ¸Đą ĐżŃ€ĐľŃ‚ĐľŃ‚Đ¸Đż.' }, { "title": 'ĐśĐ°ŃŃŃ‚Đ°Đ±Đ¸Ń€ĐľĐ˛Đ°Đ˝Đ¸Đµ', "desc": 'ĐźŃ€Đ¸Đ˛Đ»ĐµĐşĐ°ĐąŃ‚Đµ ĐżĐľĐ»ŃŚĐ·ĐľĐ˛Đ°Ń‚ĐµĐ»ĐµĐą Đ¸ Đ´ĐľŃ…ĐľĐ´.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'ĐšĐľĐżĐ¸Ń€Đ°ĐąŃ‚Đ¸Đ˝Đł', "shortDesc": 'ĐžĐ˛Đ»Đ°Đ´ĐµĐąŃ‚Đµ Đ¸ŃĐşŃŃŃŃ‚Đ˛ĐľĐĽ ŃĐ±ĐµĐ¶Đ´ĐµĐ˝Đ¸ŃŹ, Ń‡Ń‚ĐľĐ±Ń‹ ĐżŃ€ĐľĐ´Đ°Đ˛Đ°Ń‚ŃŚ Ń‡Ń‚Đľ ŃĐłĐľĐ´Đ˝Đľ ŃĐ»ĐľĐ˛Đ°ĐĽĐ¸.', "fullDesc": 'ĐĄĐľŃ€ĐľŃĐ¸Đą Ń‚ĐµĐşŃŃ‚ ĐżŃ€Đ¸Đ˝ĐľŃĐ¸Ń‚ ĐĽĐ¸Đ»Đ»Đ¸ĐľĐ˝Ń‹. ĐĐ·ŃŃ‡Đ¸Ń‚Đµ ĐżŃĐ¸Ń…ĐľĐ»ĐľĐłĐ¸ŃŽ ŃĐ±ĐµĐ¶Đ´ĐµĐ˝Đ¸ŃŹ, ĐşĐ°Đş ĐżĐ¸ŃĐ°Ń‚ŃŚ Ń†ĐµĐ»ĐµĐ˛Ń‹Đµ ŃŃ‚Ń€Đ°Đ˝Đ¸Ń†Ń‹, ŃŤĐ»ĐµĐşŃ‚Ń€ĐľĐ˝Đ˝Ń‹Đµ ĐżĐ¸ŃŃŚĐĽĐ° Đ¸ Ń€ĐµĐşĐ»Đ°ĐĽŃ, ĐşĐľŃ‚ĐľŃ€Ń‹Đµ ĐżŃ€ĐµĐ˛Ń€Đ°Ń‰Đ°ŃŽŃ‚ Đ˝ĐµĐ·Đ˝Đ°ĐşĐľĐĽŃ†ĐµĐ˛ Đ˛ ĐşĐ»Đ¸ĐµĐ˝Ń‚ĐľĐ˛ Đ·Đ° Đ˛Ń‹ŃĐľĐşĐ¸Đµ ĐłĐľĐ˝ĐľŃ€Đ°Ń€Ń‹.', "steps": [ { "title": 'ĐźŃĐ¸Ń…ĐľĐ»ĐľĐłĐ¸ŃŹ', "desc": 'ĐźĐľĐąĐĽĐ¸Ń‚Đµ, Ń‡Ń‚Đľ Đ´Đ˛Đ¸Đ¶ĐµŃ‚ Đ´ĐµĐąŃŃ‚Đ˛Đ¸ĐµĐĽ.' }, { "title": 'ĐˇŃ‚Ń€ŃĐşŃ‚ŃŃ€Ń‹', "desc": 'ĐžĐ˛Đ»Đ°Đ´ĐµĐąŃ‚Đµ ĐżŃ€ĐľĐ˛ĐµŃ€ĐµĐ˝Đ˝Ń‹ĐĽĐ¸ ŃŃ‚Ń€ŃĐşŃ‚ŃŃ€Đ°ĐĽĐ¸ ĐżĐ¸ŃŃŚĐĽĐ°.' }, { "title": 'ĐšĐ»Đ¸ĐµĐ˝Ń‚Ń‹', "desc": 'ĐźĐľĐ»ŃŃ‡Đ°ĐąŃ‚Đµ Đ˛Ń‹ŃĐľĐşĐľĐľĐżĐ»Đ°Ń‡Đ¸Đ˛Đ°ĐµĐĽŃ‹Đµ Đ·Đ°ĐşĐ°Đ·Ń‹.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Đ¦Đ¸Ń„Ń€ĐľĐ˛ĐľĐą ĐśĐ°Ń€ĐşĐµŃ‚Đ¸Đ˝Đł', "shortDesc": 'Đ—Đ°ĐżŃŃĐşĐ°ĐąŃ‚Đµ ĐżŃ€Đ¸Đ±Ń‹Đ»ŃŚĐ˝ŃŃŽ Ń€ĐµĐşĐ»Đ°ĐĽŃ Đ¸ ŃĐżŃ€Đ°Đ˛Đ»ŃŹĐąŃ‚Đµ Ń€ĐľŃŃ‚ĐľĐĽ ĐşĐľĐĽĐżĐ°Đ˝Đ¸Đą.', "fullDesc": 'ĐšĐ°Đ¶Đ´ĐľĐĽŃ Đ±Đ¸Đ·Đ˝ĐµŃŃ Đ˝ŃĐ¶Đ˝Đľ Đ±ĐľĐ»ŃŚŃĐµ ĐşĐ»Đ¸ĐµĐ˝Ń‚ĐľĐ˛. ĐžŃ‚ĐşŃ€ĐľĐąŃ‚Đµ Đ°ĐłĐµĐ˝Ń‚ŃŃ‚Đ˛Đľ (SMMA), ĐżĐľĐĽĐľĐłĐ°ŃŹ Đ±Ń€ĐµĐ˝Đ´Đ°ĐĽ Ń€Đ°ŃŃ‚Đ¸ Ń‡ĐµŃ€ĐµĐ· Facebook Ads, TikTok Ads Đ¸ Google Ads. Đ’Ń‹ŃĐľĐşĐ¸Đą ŃĐżŃ€ĐľŃ, ĐĽĐ°ŃŃŃ‚Đ°Đ±Đ¸Ń€ŃĐµĐĽĐľŃŃ‚ŃŚ.', "steps": [ { "title": 'ĐˇŃ‚Ń€Đ°Ń‚ĐµĐłĐ¸ŃŹ', "desc": 'ĐŁŃ‡Đ¸Ń‚ĐµŃŃŚ Đ·Đ°ĐżŃŃĐşĐ°Ń‚ŃŚ ĐżŃ€Đ¸Đ±Ń‹Đ»ŃŚĐ˝Ń‹Đµ ĐşĐ°ĐĽĐżĐ°Đ˝Đ¸Đ¸.' }, { "title": 'ĐŁŃĐ»ŃĐłĐ¸', "desc": 'Đ“ĐµĐ˝ĐµŃ€Đ¸Ń€ŃĐąŃ‚Đµ Đ»Đ¸Đ´Ń‹ Đ´Đ»ŃŹ ĐşĐ»Đ¸ĐµĐ˝Ń‚ĐľĐ˛.' }, { "title": 'Đ ĐľŃŃ‚', "desc": 'ĐˇĐľĐ·Đ´Đ°ĐąŃ‚Đµ ĐşĐľĐĽĐ°Đ˝Đ´Ń Đ´Đ»ŃŹ Ń€Đ°Đ±ĐľŃ‚Ń‹.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Đ˘Ń€ĐµĐąĐ´Đ¸Đ˝Đł', "shortDesc": 'ĐĐ˝Đ°Đ»Đ¸Đ·Đ¸Ń€ŃĐąŃ‚Đµ Ń€Ń‹Đ˝ĐşĐ¸ Đ¸ Ń‚ĐľŃ€ĐłŃĐąŃ‚Đµ ĐšŃ€Đ¸ĐżŃ‚Đľ, Đ¤ĐľŃ€ĐµĐşŃ Đ¸Đ»Đ¸ ĐĐ˝Đ´ĐµĐşŃĐ°ĐĽĐ¸.', "fullDesc": 'ĐžĐ˛Đ»Đ°Đ´ĐµĐąŃ‚Đµ ĐşĐ»ŃŽŃ‡ĐµĐ˛Ń‹ĐĽĐ¸ ĐşĐľĐ˝Ń†ĐµĐżŃ†Đ¸ŃŹĐĽĐ¸ Ń‚ĐµŃ…Đ˝Đ¸Ń‡ĐµŃĐşĐľĐłĐľ Đ°Đ˝Đ°Đ»Đ¸Đ·Đ°. ĐĐ·ŃŃ‡Đ¸Ń‚Đµ ŃĐżŃ€Đ°Đ˛Đ»ĐµĐ˝Đ¸Đµ Ń€Đ¸ŃĐşĐ°ĐĽĐ¸, ĐżŃĐ¸Ń…ĐľĐ»ĐľĐłĐ¸ŃŽ Đ¸ ŃŃ‚Ń€Đ°Ń‚ĐµĐłĐ¸Đ¸, Ń‡Ń‚ĐľĐ±Ń‹ ŃĐ°ĐĽĐľŃŃ‚ĐľŃŹŃ‚ĐµĐ»ŃŚĐ˝Đľ ĐżĐľĐ»ŃŃ‡Đ°Ń‚ŃŚ ĐżŃ€Đ¸Đ±Ń‹Đ»ŃŚ ĐľŃ‚ Đ´Đ˛Đ¸Đ¶ĐµĐ˝Đ¸Đą Ń€Ń‹Đ˝ĐşĐ°.', "steps": [ { "title": 'ĐĐ˝Đ°Đ»Đ¸Đ·', "desc": 'Đ§Đ¸Ń‚Đ°ĐąŃ‚Đµ ĐłŃ€Đ°Ń„Đ¸ĐşĐ¸ Đ¸ ŃŃ‚Ń€ŃĐşŃ‚ŃŃ€Ń Ń€Ń‹Đ˝ĐşĐ°.' }, { "title": 'Đ Đ¸ŃĐş', "desc": 'ĐˇĐ˝Đ°Ń‡Đ°Đ»Đ° Đ·Đ°Ń‰Đ¸Ń‚Đ¸Ń‚Đµ ŃĐ˛ĐľĐą ĐşĐ°ĐżĐ¸Ń‚Đ°Đ».' }, { "title": 'ĐŃĐżĐľĐ»Đ˝ĐµĐ˝Đ¸Đµ', "desc": 'ĐˇĐľĐ˛ĐµŃ€ŃĐ°ĐąŃ‚Đµ ŃĐ´ĐµĐ»ĐşĐ¸ Ń Đ˛Ń‹ŃĐľĐşĐľĐą Đ˛ĐµŃ€ĐľŃŹŃ‚Đ˝ĐľŃŃ‚ŃŚŃŽ.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'ĐˇĐľĐ·Đ´Đ°Đ˝Đ¸Đµ ĐšĐľĐ˝Ń‚ĐµĐ˝Ń‚Đ°', "shortDesc": 'ĐˇĐľĐ·Đ´Đ°ĐąŃ‚Đµ Đ»Đ¸Ń‡Đ˝Ń‹Đą Đ±Ń€ĐµĐ˝Đ´ Đ¸ ĐĽĐľĐ˝ĐµŃ‚Đ¸Đ·Đ¸Ń€ŃĐąŃ‚Đµ Đ°ŃĐ´Đ¸Ń‚ĐľŃ€Đ¸ŃŽ.', "fullDesc": 'Đ’Đ˝Đ¸ĐĽĐ°Đ˝Đ¸Đµ â€” ŃŤŃ‚Đľ Đ˝ĐľĐ˛Đ°ŃŹ Đ˛Đ°Đ»ŃŽŃ‚Đ°. ĐŁĐ·Đ˝Đ°ĐąŃ‚Đµ, ĐşĐ°Đş ŃĐľĐ·Đ´Đ°Đ˛Đ°Ń‚ŃŚ Đ˛Đ¸Ń€ŃŃĐ˝Ń‹Đą ĐşĐľŃ€ĐľŃ‚ĐşĐ¸Đą ĐşĐľĐ˝Ń‚ĐµĐ˝Ń‚, Đ˝Đ°Đ±Đ¸Ń€Đ°Ń‚ŃŚ Đ»ĐľŃŹĐ»ŃŚĐ˝Ń‹Ń… ĐżĐľĐ´ĐżĐ¸ŃŃ‡Đ¸ĐşĐľĐ˛ Đ¸ Đ·Đ°Ń€Đ°Đ±Đ°Ń‚Ń‹Đ˛Đ°Ń‚ŃŚ Đ˝Đ° ŃĐżĐľĐ˝ŃĐľŃ€ŃŃ‚Đ˛Đµ Đ¸Đ»Đ¸ ŃĐľĐ±ŃŃ‚Đ˛ĐµĐ˝Đ˝Ń‹Ń… ĐżŃ€ĐľĐ´ŃĐşŃ‚Đ°Ń….', "steps": [ { "title": 'Đ’Đ¸Ń€ŃŃĐ˝Ń‹Đµ ĐˇŃ†ĐµĐ˝Đ°Ń€Đ¸Đ¸', "desc": 'ĐśĐłĐ˝ĐľĐ˛ĐµĐ˝Đ˝Đľ Ń†ĐµĐżĐ»ŃŹĐąŃ‚Đµ Đ·Ń€Đ¸Ń‚ĐµĐ»ĐµĐą.' }, { "title": 'ĐźŃ€ĐľĐ´Đ°ĐşŃĐ˝', "desc": 'ĐˇĐ˝Đ¸ĐĽĐ°ĐąŃ‚Đµ Đ¸ ĐĽĐľĐ˝Ń‚Đ¸Ń€ŃĐąŃ‚Đµ ĐşĐ°Ń‡ĐµŃŃ‚Đ˛ĐµĐ˝Đ˝Ń‹Đµ ĐşĐ»Đ¸ĐżŃ‹.' }, { "title": 'ĐśĐľĐ˝ĐµŃ‚Đ¸Đ·Đ°Ń†Đ¸ŃŹ', "desc": 'ĐźŃ€ĐµĐ˛Ń€Đ°Ń‰Đ°ĐąŃ‚Đµ ĐżŃ€ĐľŃĐĽĐľŃ‚Ń€Ń‹ Đ˛ Đ´ĐľŃ…ĐľĐ´.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'ĐźŃ€ĐľĐ´Đ°Đ˛Đ°ĐąŃ‚Đµ Ń„Đ¸Đ·Đ¸Ń‡ĐµŃĐşĐ¸Đµ Ń‚ĐľĐ˛Đ°Ń€Ń‹ ĐżĐľ Đ˛ŃĐµĐĽŃ ĐĽĐ¸Ń€Ń Đ±ĐµĐ· ŃĐşĐ»Đ°Đ´Đ°.', "fullDesc": 'Đ—Đ°ĐżŃŃŃ‚Đ¸Ń‚Đµ Đ´Ń€ĐľĐżŃĐ¸ĐżĐżĐ¸Đ˝Đł Đ¸Đ»Đ¸ Đ±Ń€ĐµĐ˝Đ´ĐľĐ˛Ń‹Đą ĐĽĐ°ĐłĐ°Đ·Đ¸Đ˝. ĐĐ·ŃŃ‡Đ¸Ń‚Đµ ĐżĐľĐ¸ŃĐş ĐżŃ€ĐľĐ´ŃĐşŃ‚ĐľĐ˛, ĐľŃ‚Đ˝ĐľŃĐµĐ˝Đ¸ŃŹ Ń ĐżĐľŃŃ‚Đ°Đ˛Ń‰Đ¸ĐşĐ°ĐĽĐ¸ Đ¸ ĐşĐ°Đş ŃĐľĐ·Đ´Đ°Ń‚ŃŚ ĐşĐľĐ˝Đ˛ĐµŃ€ŃĐ¸ĐľĐ˝Đ˝Ń‹Đą ĐĽĐ°ĐłĐ°Đ·Đ¸Đ˝ Đ˝Đ° Shopify.', "steps": [ { "title": 'ĐźĐľĐ¸ŃĐş ĐźŃ€ĐľĐ´ŃĐşŃ‚Đ°', "desc": 'ĐťĐ°ĐąĐ´Đ¸Ń‚Đµ Đ˛Ń‹Đ¸ĐłŃ€Ń‹ŃĐ˝Ń‹Đµ Ń‚ĐľĐ˛Đ°Ń€Ń‹.' }, { "title": 'ĐˇĐľĐ·Đ´Đ°Đ˝Đ¸Đµ ĐśĐ°ĐłĐ°Đ·Đ¸Đ˝Đ°', "desc": 'ĐˇĐľĐ·Đ´Đ°ĐąŃ‚Đµ ŃĐ°ĐąŃ‚ Ń Đ˛Ń‹ŃĐľĐşĐľĐą ĐşĐľĐ˝Đ˛ĐµŃ€ŃĐ¸ĐµĐą.' }, { "title": 'Đ—Đ°ĐżŃŃĐş', "desc": 'ĐźŃ€Đ¸Đ˛Đ»ĐµĐşĐ°ĐąŃ‚Đµ Ń‚Ń€Đ°Ń„Đ¸Đş Đ¸ Đ˛Ń‹ĐżĐľĐ»Đ˝ŃŹĐąŃ‚Đµ Đ·Đ°ĐşĐ°Đ·Ń‹.' } ] }
    ],
    "sr": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS Graditelj', "shortDesc": 'Kreiraj i skaliraj softverske proizvode koji donose ponavljajuÄ‡e prihode.', "fullDesc": 'Software as a Service (SaaS) je zlatni standard digitalnog prihoda. NauÄŤi kako prepoznati trĹľiĹˇne praznine, graditi koristeÄ‡i no-code ili kod alate, i skalirati pretplatniÄŤki biznis.', "steps": [ { "title": 'Ideacija', "desc": 'PronaÄ‘i profitabilne probleme za rjeĹˇavanje.' }, { "title": 'MVP Izrada', "desc": 'Brzo lansiraj funkcionalan prototip.' }, { "title": 'Skaliranje', "desc": 'Stekni korisnike i ponavljajuÄ‡e prihode.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Savladaj umjetnost uvjeravanja da prodaĹˇ bilo Ĺˇta rijeÄŤima.', "fullDesc": 'Dobar tekst donosi milione. NauÄŤi psihologiju iza uvjeravanja, kako pisati landing stranice, emailove i oglase koji pretvaraju strance u kupce za visoke honorare.', "steps": [ { "title": 'Psihologija', "desc": 'Razumi Ĺˇta pokreÄ‡e akciju.' }, { "title": 'Okviri', "desc": 'Savladaj dokazane strukture pisanja.' }, { "title": 'Akvizicija Klijenata', "desc": 'Osiguraj visoko plaÄ‡ene ugovore.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Digitalni Marketing', "shortDesc": 'Vodi profitabilne oglase i upravljaj rastom za biznise.', "fullDesc": 'Svaki biznis treba viĹˇe kupaca. Pokreni agenciju (SMMA) pomaĹľuÄ‡i brendovima da rastu kroz Facebook Ads, TikTok Ads i Google Ads. Velika potraĹľnja, skalabilna usluga.', "steps": [ { "title": 'Strategija Oglasa', "desc": 'NauÄŤi voditi profitabilne kampanje.' }, { "title": 'Isporuka Usluge', "desc": 'GeneriĹˇi lidove za klijente.' }, { "title": 'Rast Agencije', "desc": 'Izgradi tim za ispunjavajuÄ‡i rad.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Finansijsko Trgovanje', "shortDesc": 'Analiziraj trĹľiĹˇta i trguj Kripto, Forex ili Indeksima.', "fullDesc": 'Savladaj kljuÄŤne koncepte tehniÄŤke analize za navigaciju finansijskim trĹľiĹˇtima. NauÄŤi upravljanje rizikom, psihologiju i strategije da profitiraĹˇ od trĹľiĹˇnih kretanja samostalno.', "steps": [ { "title": 'Analiza', "desc": 'ÄŚitaj grafikone i strukturu trĹľiĹˇta.' }, { "title": 'Upravljanje Rizikom', "desc": 'Prvo zaĹˇtiti svoj kapital.' }, { "title": 'IzvrĹˇenje', "desc": 'Postavljaj trgovine visoke vjerovatnoÄ‡e.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Kreiranje SadrĹľaja', "shortDesc": 'Izgradi liÄŤni brend i monetizuj svoju publiku.', "fullDesc": 'PaĹľnja je nova valuta. NauÄŤi kako kreirati viralni kratki sadrĹľaj, izgraditi lojalne pratioce i zaraditi kroz sponzorstva, partnere ili vlastite proizvode.', "steps": [ { "title": 'Viralni Skripti', "desc": 'Odmah privuci gledaoce.' }, { "title": 'Produkcija', "desc": 'Snimaj i montiraj klipove visokog kvaliteta.' }, { "title": 'Monetizacija', "desc": 'Pretvori preglede u prihod.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Prodaji fiziÄŤke proizvode globalno bez drĹľanja zaliha.', "fullDesc": 'Pokreni dropshipping ili brendiranu web trgovinu. NauÄŤi istraĹľivanje proizvoda, odnose s dobavljaÄŤima i kako izgraditi konvertujuÄ‡u trgovinu na Shopify-u.', "steps": [ { "title": 'Potraga za Proizvodima', "desc": 'PronaÄ‘i pobjedniÄŤke proizvode.' }, { "title": 'Izrada Trgovine', "desc": 'Dizajniraj stranicu s visokom konverzijom.' }, { "title": 'Lansiranje', "desc": 'Dovedi saobraÄ‡aj i ispuni narudĹľbe.' } ] }
    ],
    "sk": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS Tvorca', "shortDesc": 'VytvĂˇrajte a ĹˇkĂˇlujte softvĂ©rovĂ© produkty, ktorĂ© generujĂş opakujĂşce sa prĂ­jmy.', "fullDesc": 'Software as a Service (SaaS) je zlatĂ˝ Ĺˇtandard digitĂˇlneho prĂ­jmu. NauÄŤte sa identifikovaĹĄ medzery na trhu, budovaĹĄ pomocou no-code alebo kĂłdovacĂ­ch nĂˇstrojov a ĹˇkĂˇlovaĹĄ predplatiteÄľskĂ© podnikanie.', "steps": [ { "title": 'Idea', "desc": 'NĂˇjdite ziskovĂ© problĂ©my na rieĹˇenie.' }, { "title": 'Tvorba MVP', "desc": 'RĂ˝chlo spustite funkÄŤnĂ˝ prototyp.' }, { "title": 'Ĺ kĂˇlovanie', "desc": 'ZĂ­skajte pouĹľĂ­vateÄľov a opakujĂşce sa prĂ­jmy.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'OvlĂˇdnite umenie presviedÄŤania a predĂˇvajte ÄŤokoÄľvek slovami.', "fullDesc": 'DobrĂ˝ text zarĂˇba miliĂłny. Spoznajte psycholĂłgiu presviedÄŤania, ako pĂ­saĹĄ vstupnĂ© strĂˇnky, e-maily a reklamy, ktorĂ© menia cudzincov na zĂˇkaznĂ­kov za vysokĂ© poplatky.', "steps": [ { "title": 'PsycholĂłgia', "desc": 'Pochopte, ÄŤo pohĂˇĹa akciu.' }, { "title": 'RĂˇmce', "desc": 'OvlĂˇdnite osvedÄŤenĂ© ĹˇtruktĂşry pĂ­sania.' }, { "title": 'ZĂ­skavanie klientov', "desc": 'ZĂ­skajte vysoko platenĂ© zĂˇkazky.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'DigitĂˇlny Marketing', "shortDesc": 'Spravujte ziskovĂ© reklamy a riaÄŹte rast firiem.', "fullDesc": 'KaĹľdĂˇ firma potrebuje viac zĂˇkaznĂ­kov. ZaloĹľte agentĂşru (SMMA) pomĂˇhajĂşcu znaÄŤkĂˇm rĂˇsĹĄ prostrednĂ­ctvom Facebook Ads, TikTok Ads a Google Ads. VysokĂ˝ dopyt, ĹˇkĂˇlovateÄľnĂˇ sluĹľba.', "steps": [ { "title": 'ReklamnĂˇ stratĂ©gia', "desc": 'NauÄŤte sa riadiĹĄ ziskovĂ© kampane.' }, { "title": 'Poskytovanie sluĹľieb', "desc": 'Generujte leady pre klientov.' }, { "title": 'Rast agentĂşry', "desc": 'Vybudujte tĂ­m pre naplĹujĂşcu prĂˇcu.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'FinanÄŤnĂ© Obchodovanie', "shortDesc": 'Analyzujte trhy a obchodujte Krypto, Forex alebo Indexy.', "fullDesc": 'OvlĂˇdnite kÄľĂşÄŤovĂ© koncepty technickej analĂ˝zy pre navigĂˇciu na finanÄŤnĂ˝ch trhoch. NauÄŤte sa riadenie rizĂ­k, psycholĂłgiu a stratĂ©gie, ako nezĂˇvisle profitovaĹĄ z trhovĂ˝ch pohybov.', "steps": [ { "title": 'AnalĂ˝za', "desc": 'ÄŚĂ­tajte grafy a ĹˇtruktĂşru trhu.' }, { "title": 'Riadenie rizĂ­k', "desc": 'Najprv chrĂˇĹte svoj kapitĂˇl.' }, { "title": 'ExekĂşcia', "desc": 'VykonĂˇvajte obchody s vysokou pravdepodobnosĹĄou.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'Tvorba Obsahu', "shortDesc": 'Vybudujte osobnĂş znaÄŤku a monetizujte svoje publikum.', "fullDesc": 'PozornosĹĄ je novĂˇ mena. NauÄŤte sa vytvĂˇraĹĄ virĂˇlne krĂˇtke videĂˇ, budovaĹĄ vernĂ˝ch sledovateÄľov a zarĂˇbaĹĄ prostrednĂ­ctvom sponzorstva, affiliate alebo vlastnĂ˝ch produktov.', "steps": [ { "title": 'VirĂˇlne scenĂˇre', "desc": 'OkamĹľite zaujmite divĂˇkov.' }, { "title": 'Produkcia', "desc": 'NatĂˇÄŤajte a strihajte kvalitnĂ© klipy.' }, { "title": 'MonetizĂˇcia', "desc": 'PremeĹte zhliadnutia na prĂ­jem.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'PredĂˇvajte fyzickĂ© produkty globĂˇlne bez drĹľania zĂˇsob.', "fullDesc": 'Spustite dropshippingovĂ˝ alebo znaÄŤkovĂ˝ e-shop. NauÄŤte sa prieskum produktov, vzĹĄahy s dodĂˇvateÄľmi a ako vybudovaĹĄ konverznĂ˝ obchod na Shopify.', "steps": [ { "title": 'HÄľadanie produktov', "desc": 'NĂˇjdite vĂ­ĹĄaznĂ© produkty.' }, { "title": 'Stavba obchodu', "desc": 'Navrhnite web s vysokou konverziou.' }, { "title": 'Spustenie', "desc": 'PriveÄŹte nĂˇvĹˇtevnosĹĄ a vybavujte objednĂˇvky.' } ] }
    ],
    "es": [
        { "id": 'saas', "icon": 'đź’»', "title": 'Creador SaaS', "shortDesc": 'Crea y escala productos de software que generen ingresos recurrentes.', "fullDesc": 'El Software como Servicio (SaaS) es el estĂˇndar de oro de los ingresos digitales. Aprende a identificar huecos en el mercado, construir con herramientas sin cĂłdigo o con cĂłdigo, y escalar un negocio de suscripciĂłn.', "steps": [ { "title": 'IdeaciĂłn', "desc": 'Encuentra problemas rentables para resolver.' }, { "title": 'ConstrucciĂłn MVP', "desc": 'Lanza un prototipo funcional rĂˇpido.' }, { "title": 'Escalado', "desc": 'Adquiere usuarios e ingresos recurrentes.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'Copywriting', "shortDesc": 'Domina el arte de la persuasiĂłn para vender cualquier cosa con palabras.', "fullDesc": 'Un buen texto genera millones. Aprende la psicologĂ­a detrĂˇs de la persuasiĂłn, cĂłmo escribir pĂˇginas de aterrizaje, correos electrĂłnicos y anuncios que conviertan extraĂ±os en clientes.', "steps": [ { "title": 'PsicologĂ­a', "desc": 'Entiende quĂ© impulsa la acciĂłn.' }, { "title": 'Marcos', "desc": 'Domina estructuras de escritura probadas.' }, { "title": 'AdquisiciĂłn', "desc": 'Consigue contratos bien pagados.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Marketing Digital', "shortDesc": 'Ejecuta anuncios rentables y gestiona el crecimiento de empresas.', "fullDesc": 'Todo negocio necesita mĂˇs clientes. Inicia una agencia (SMMA) ayudando a marcas a crecer a travĂ©s de Facebook Ads, TikTok Ads y Google Ads. Alta demanda, servicio escalable.', "steps": [ { "title": 'Estrategia', "desc": 'Aprende a ejecutar campaĂ±as rentables.' }, { "title": 'Entrega', "desc": 'Genera clientes potenciales.' }, { "title": 'Crecimiento', "desc": 'Construye un equipo para el trabajo.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Trading Financiero', "shortDesc": 'Analiza mercados y opera Cripto, Forex o ĂŤndices.', "fullDesc": 'Domina conceptos clave de anĂˇlisis tĂ©cnico para navegar los mercados financieros. Aprende gestiĂłn de riesgos, psicologĂ­a y estrategias para beneficiarte de los movimientos del mercado.', "steps": [ { "title": 'AnĂˇlisis', "desc": 'Lee grĂˇficos y estructura de mercado.' }, { "title": 'Riesgo', "desc": 'Protege tu capital primero.' }, { "title": 'EjecuciĂłn', "desc": 'Coloca operaciones de alta probabilidad.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'CreaciĂłn de Contenido', "shortDesc": 'Construye una marca personal y monetiza tu audiencia.', "fullDesc": 'La atenciĂłn es la nueva moneda. Aprende a crear contenido viral corto, construir seguidores leales y ganar a travĂ©s de patrocinios, afiliados o tus propios productos.', "steps": [ { "title": 'Guiones Virales', "desc": 'Engancha a los espectadores al instante.' }, { "title": 'ProducciĂłn', "desc": 'Graba y edita clips de alta calidad.' }, { "title": 'MonetizaciĂłn', "desc": 'Convierte visitas en ingresos.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'Vende productos fĂ­sicos globalmente sin inventario.', "fullDesc": 'Inicia una tienda de dropshipping o de marca. Aprende investigaciĂłn de productos, relaciones con proveedores y cĂłmo construir una tienda que convierta en Shopify.', "steps": [ { "title": 'Caza de Productos', "desc": 'Encuentra productos ganadores.' }, { "title": 'ConstrucciĂłn', "desc": 'DiseĂ±a un sitio de alta conversiĂłn.' }, { "title": 'Lanzamiento', "desc": 'Genera trĂˇfico y cumple pedidos.' } ] }
    ],
    "uk": [
        { "id": 'saas', "icon": 'đź’»', "title": 'SaaS Đ ĐľĐ·Ń€ĐľĐ±Đ˝Đ¸Đş', "shortDesc": 'ĐˇŃ‚Đ˛ĐľŃ€ŃŽĐąŃ‚Đµ Ń‚Đ° ĐĽĐ°ŃŃŃ‚Đ°Đ±ŃĐąŃ‚Đµ ĐżŃ€ĐľĐłŃ€Đ°ĐĽĐ˝Ń– ĐżŃ€ĐľĐ´ŃĐşŃ‚Đ¸ Đ· Ń€ĐµĐłŃĐ»ŃŹŃ€Đ˝Đ¸ĐĽ Đ´ĐľŃ…ĐľĐ´ĐľĐĽ.', "fullDesc": 'ĐźŃ€ĐľĐłŃ€Đ°ĐĽĐ˝Đµ Đ·Đ°Đ±ĐµĐ·ĐżĐµŃ‡ĐµĐ˝Đ˝ŃŹ ŃŹĐş ĐżĐľŃĐ»ŃĐłĐ° (SaaS) â€” Ń†Đµ Đ·ĐľĐ»ĐľŃ‚Đ¸Đą ŃŃ‚Đ°Đ˝Đ´Đ°Ń€Ń‚ Ń†Đ¸Ń„Ń€ĐľĐ˛ĐľĐłĐľ Đ´ĐľŃ…ĐľĐ´Ń. Đ”Ń–Đ·Đ˝Đ°ĐąŃ‚ĐµŃŃŹ, ŃŹĐş Đ·Đ˝Đ°Ń…ĐľĐ´Đ¸Ń‚Đ¸ Ń€Đ¸Đ˝ĐşĐľĐ˛Ń– Đ˝Ń–ŃŃ–, ŃŃ‚Đ˛ĐľŃ€ŃŽĐ˛Đ°Ń‚Đ¸ Đ·Đ° Đ´ĐľĐżĐľĐĽĐľĐłĐľŃŽ no-code Đ°Đ±Đľ ĐşĐľĐ´Ń Ń‚Đ° ĐĽĐ°ŃŃŃ‚Đ°Đ±ŃĐ˛Đ°Ń‚Đ¸ Đ±Ń–Đ·Đ˝ĐµŃ Đ·Đ° ĐżĐµŃ€ĐµĐ´ĐżĐ»Đ°Ń‚ĐľŃŽ.', "steps": [ { "title": 'Đ†Đ´ĐµŃŹ', "desc": 'Đ—Đ˝Đ°ĐąĐ´Ń–Ń‚ŃŚ ĐżŃ€Đ¸Đ±ŃŃ‚ĐşĐľĐ˛Ń– ĐżŃ€ĐľĐ±Đ»ĐµĐĽĐ¸ Đ´Đ»ŃŹ Đ˛Đ¸Ń€Ń–ŃĐµĐ˝Đ˝ŃŹ.' }, { "title": 'ĐˇŃ‚Đ˛ĐľŃ€ĐµĐ˝Đ˝ŃŹ MVP', "desc": 'Đ¨Đ˛Đ¸Đ´ĐşĐľ Đ·Đ°ĐżŃŃŃ‚Ń–Ń‚ŃŚ ĐżŃ€Đ°Ń†ŃŽŃŽŃ‡Đ¸Đą ĐżŃ€ĐľŃ‚ĐľŃ‚Đ¸Đż.' }, { "title": 'ĐśĐ°ŃŃŃ‚Đ°Đ±ŃĐ˛Đ°Đ˝Đ˝ŃŹ', "desc": 'Đ—Đ°Đ»ŃŃ‡Đ°ĐąŃ‚Đµ ĐşĐľŃ€Đ¸ŃŃ‚ŃĐ˛Đ°Ń‡Ń–Đ˛ Ń‚Đ° Đ´ĐľŃ…Ń–Đ´.' } ] },
        { "id": 'copy', "icon": 'âśŤď¸Ź', "title": 'ĐšĐľĐżŃ–Ń€Đ°ĐąŃ‚Đ¸Đ˝Đł', "shortDesc": 'ĐžĐżĐ°Đ˝ŃĐąŃ‚Đµ ĐĽĐ¸ŃŃ‚ĐµŃ†Ń‚Đ˛Đľ ĐżĐµŃ€ĐµĐşĐľĐ˝Đ°Đ˝Đ˝ŃŹ, Ń‰ĐľĐ± ĐżŃ€ĐľĐ´Đ°Đ˛Đ°Ń‚Đ¸ Đ±ŃĐ´ŃŚ-Ń‰Đľ ŃĐ»ĐľĐ˛Đ°ĐĽĐ¸.', "fullDesc": 'ĐĄĐľŃ€ĐľŃĐ¸Đą Ń‚ĐµĐşŃŃ‚ ĐżŃ€Đ¸Đ˝ĐľŃĐ¸Ń‚ŃŚ ĐĽŃ–Đ»ŃŚĐąĐľĐ˝Đ¸. Đ’Đ¸Đ˛Ń‡Ń–Ń‚ŃŚ ĐżŃĐ¸Ń…ĐľĐ»ĐľĐłŃ–ŃŽ ĐżĐµŃ€ĐµĐşĐľĐ˝Đ°Đ˝Đ˝ŃŹ, ŃŹĐş ĐżĐ¸ŃĐ°Ń‚Đ¸ Ń†Ń–Đ»ŃŚĐľĐ˛Ń– ŃŃ‚ĐľŃ€Ń–Đ˝ĐşĐ¸, ĐµĐ»ĐµĐşŃ‚Ń€ĐľĐ˝Đ˝Ń– Đ»Đ¸ŃŃ‚Đ¸ Ń‚Đ° Ń€ĐµĐşĐ»Đ°ĐĽŃ, ŃŹĐşŃ– ĐżĐµŃ€ĐµŃ‚Đ˛ĐľŃ€ŃŽŃŽŃ‚ŃŚ Đ˝ĐµĐ·Đ˝Đ°ĐąĐľĐĽŃ†Ń–Đ˛ Đ˝Đ° ĐşĐ»Ń–Ń”Đ˝Ń‚Ń–Đ˛ Đ·Đ° Đ˛Đ¸ŃĐľĐşŃ– ĐłĐľĐ˝ĐľŃ€Đ°Ń€Đ¸.', "steps": [ { "title": 'ĐźŃĐ¸Ń…ĐľĐ»ĐľĐłŃ–ŃŹ', "desc": 'Đ—Ń€ĐľĐ·ŃĐĽŃ–ĐąŃ‚Đµ, Ń‰Đľ ŃĐżĐľĐ˝ŃĐşĐ°Ń” Đ´Đľ Đ´Ń–Ń—.' }, { "title": 'ĐˇŃ‚Ń€ŃĐşŃ‚ŃŃ€Đ¸', "desc": 'ĐžĐżĐ°Đ˝ŃĐąŃ‚Đµ ĐżĐµŃ€ĐµĐ˛Ń–Ń€ĐµĐ˝Ń– ŃŃ‚Ń€ŃĐşŃ‚ŃŃ€Đ¸ ĐżĐ¸ŃŃŚĐĽĐ°.' }, { "title": 'ĐšĐ»Ń–Ń”Đ˝Ń‚Đ¸', "desc": 'ĐžŃ‚Ń€Đ¸ĐĽŃĐąŃ‚Đµ Đ˛Đ¸ŃĐľĐşĐľĐľĐżĐ»Đ°Ń‡ŃĐ˛Đ°Đ˝Ń– Đ·Đ°ĐĽĐľĐ˛Đ»ĐµĐ˝Đ˝ŃŹ.' } ] },
        { "id": 'marketing', "icon": 'đź“', "title": 'Đ¦Đ¸Ń„Ń€ĐľĐ˛Đ¸Đą ĐśĐ°Ń€ĐşĐµŃ‚Đ¸Đ˝Đł', "shortDesc": 'Đ—Đ°ĐżŃŃĐşĐ°ĐąŃ‚Đµ ĐżŃ€Đ¸Đ±ŃŃ‚ĐşĐľĐ˛Ń Ń€ĐµĐşĐ»Đ°ĐĽŃ Ń‚Đ° ĐşĐµŃ€ŃĐąŃ‚Đµ Đ·Ń€ĐľŃŃ‚Đ°Đ˝Đ˝ŃŹĐĽ ĐşĐľĐĽĐżĐ°Đ˝Ń–Đą.', "fullDesc": 'ĐšĐľĐ¶Đ˝ĐľĐĽŃ Đ±Ń–Đ·Đ˝ĐµŃŃ ĐżĐľŃ‚Ń€Ń–Đ±Đ˝Đľ Đ±Ń–Đ»ŃŚŃĐµ ĐşĐ»Ń–Ń”Đ˝Ń‚Ń–Đ˛. Đ’Ń–Đ´ĐşŃ€Đ¸ĐąŃ‚Đµ Đ°ĐłĐµĐ˝Ń‚ŃŃ‚Đ˛Đľ (SMMA), Đ´ĐľĐżĐľĐĽĐ°ĐłĐ°ŃŽŃ‡Đ¸ Đ±Ń€ĐµĐ˝Đ´Đ°ĐĽ Ń€ĐľŃŃ‚Đ¸ Ń‡ĐµŃ€ĐµĐ· Facebook Ads, TikTok Ads Ń‚Đ° Google Ads. Đ’Đ¸ŃĐľĐşĐ¸Đą ĐżĐľĐżĐ¸Ń‚, ĐĽĐ°ŃŃŃ‚Đ°Đ±ĐľĐ˛Đ°Đ˝Ń–ŃŃ‚ŃŚ.', "steps": [ { "title": 'ĐˇŃ‚Ń€Đ°Ń‚ĐµĐłŃ–ŃŹ', "desc": 'Đ’Ń‡Ń–Ń‚ŃŚŃŃŹ Đ·Đ°ĐżŃŃĐşĐ°Ń‚Đ¸ ĐżŃ€Đ¸Đ±ŃŃ‚ĐşĐľĐ˛Ń– ĐşĐ°ĐĽĐżĐ°Đ˝Ń–Ń—.' }, { "title": 'ĐźĐľŃĐ»ŃĐłĐ¸', "desc": 'Đ“ĐµĐ˝ĐµŃ€ŃĐąŃ‚Đµ Đ»Ń–Đ´Đ¸ Đ´Đ»ŃŹ ĐşĐ»Ń–Ń”Đ˝Ń‚Ń–Đ˛.' }, { "title": 'Đ Ń–ŃŃ‚', "desc": 'ĐˇŃ‚Đ˛ĐľŃ€Ń–Ń‚ŃŚ ĐşĐľĐĽĐ°Đ˝Đ´Ń Đ´Đ»ŃŹ Ń€ĐľĐ±ĐľŃ‚Đ¸.' } ] },
        { "id": 'trading', "icon": 'đź“Š', "title": 'Đ˘Ń€ĐµĐąĐ´Đ¸Đ˝Đł', "shortDesc": 'ĐĐ˝Đ°Đ»Ń–Đ·ŃĐąŃ‚Đµ Ń€Đ¸Đ˝ĐşĐ¸ Ń‚Đ° Ń‚ĐľŃ€ĐłŃĐąŃ‚Đµ ĐšŃ€Đ¸ĐżŃ‚Đľ, Đ¤ĐľŃ€ĐµĐşŃ Đ°Đ±Đľ Đ†Đ˝Đ´ĐµĐşŃĐ°ĐĽĐ¸.', "fullDesc": 'ĐžĐżĐ°Đ˝ŃĐąŃ‚Đµ ĐşĐ»ŃŽŃ‡ĐľĐ˛Ń– ĐşĐľĐ˝Ń†ĐµĐżŃ†Ń–Ń— Ń‚ĐµŃ…Đ˝Ń–Ń‡Đ˝ĐľĐłĐľ Đ°Đ˝Đ°Đ»Ń–Đ·Ń. Đ’Đ¸Đ˛Ń‡Ń–Ń‚ŃŚ ŃĐżŃ€Đ°Đ˛Đ»Ń–Đ˝Đ˝ŃŹ Ń€Đ¸Đ·Đ¸ĐşĐ°ĐĽĐ¸, ĐżŃĐ¸Ń…ĐľĐ»ĐľĐłŃ–ŃŽ Ń‚Đ° ŃŃ‚Ń€Đ°Ń‚ĐµĐłŃ–Ń—, Ń‰ĐľĐ± ŃĐ°ĐĽĐľŃŃ‚Ń–ĐąĐ˝Đľ ĐľŃ‚Ń€Đ¸ĐĽŃĐ˛Đ°Ń‚Đ¸ ĐżŃ€Đ¸Đ±ŃŃ‚ĐľĐş Đ˛Ń–Đ´ Ń€ŃŃ…Ń–Đ˛ Ń€Đ¸Đ˝ĐşŃ.', "steps": [ { "title": 'ĐĐ˝Đ°Đ»Ń–Đ·', "desc": 'Đ§Đ¸Ń‚Đ°ĐąŃ‚Đµ ĐłŃ€Đ°Ń„Ń–ĐşĐ¸ Ń‚Đ° ŃŃ‚Ń€ŃĐşŃ‚ŃŃ€Ń Ń€Đ¸Đ˝ĐşŃ.' }, { "title": 'Đ Đ¸Đ·Đ¸Đş', "desc": 'ĐˇĐżĐľŃ‡Đ°Ń‚ĐşŃ Đ·Đ°Ń…Đ¸ŃŃ‚Ń–Ń‚ŃŚ ŃĐ˛Ń–Đą ĐşĐ°ĐżŃ–Ń‚Đ°Đ».' }, { "title": 'Đ’Đ¸ĐşĐľĐ˝Đ°Đ˝Đ˝ŃŹ', "desc": 'Đ—Đ´Ń–ĐąŃĐ˝ŃŽĐąŃ‚Đµ ŃĐłĐľĐ´Đ¸ Đ· Đ˛Đ¸ŃĐľĐşĐľŃŽ ĐąĐĽĐľĐ˛Ń–Ń€Đ˝Ń–ŃŃ‚ŃŽ.' } ] },
        { "id": 'content', "icon": 'đźŽĄ', "title": 'ĐˇŃ‚Đ˛ĐľŃ€ĐµĐ˝Đ˝ŃŹ ĐšĐľĐ˝Ń‚ĐµĐ˝Ń‚Ń', "shortDesc": 'ĐˇŃ‚Đ˛ĐľŃ€Ń–Ń‚ŃŚ ĐľŃĐľĐ±Đ¸ŃŃ‚Đ¸Đą Đ±Ń€ĐµĐ˝Đ´ Ń‚Đ° ĐĽĐľĐ˝ĐµŃ‚Đ¸Đ·ŃĐąŃ‚Đµ Đ°ŃĐ´Đ¸Ń‚ĐľŃ€Ń–ŃŽ.', "fullDesc": 'ĐŁĐ˛Đ°ĐłĐ° â€” Ń†Đµ Đ˝ĐľĐ˛Đ° Đ˛Đ°Đ»ŃŽŃ‚Đ°. Đ”Ń–Đ·Đ˝Đ°ĐąŃ‚ĐµŃŃŹ, ŃŹĐş ŃŃ‚Đ˛ĐľŃ€ŃŽĐ˛Đ°Ń‚Đ¸ Đ˛Ń–Ń€ŃŃĐ˝Đ¸Đą ĐşĐľŃ€ĐľŃ‚ĐşĐ¸Đą ĐşĐľĐ˝Ń‚ĐµĐ˝Ń‚, Đ˝Đ°Đ±Đ¸Ń€Đ°Ń‚Đ¸ Đ»ĐľŃŹĐ»ŃŚĐ˝Đ¸Ń… ĐżŃ–Đ´ĐżĐ¸ŃĐ˝Đ¸ĐşŃ–Đ˛ Ń‚Đ° Đ·Đ°Ń€ĐľĐ±Đ»ŃŹŃ‚Đ¸ Đ˝Đ° ŃĐżĐľĐ˝ŃĐľŃ€ŃŃ‚Đ˛Ń– Đ°Đ±Đľ Đ˛Đ»Đ°ŃĐ˝Đ¸Ń… ĐżŃ€ĐľĐ´ŃĐşŃ‚Đ°Ń….', "steps": [ { "title": 'Đ’Ń–Ń€ŃŃĐ˝Ń– ĐˇŃ†ĐµĐ˝Đ°Ń€Ń–Ń—', "desc": 'ĐśĐ¸Ń‚Ń‚Ń”Đ˛Đľ Ń‡Ń–ĐżĐ»ŃŹĐąŃ‚Đµ ĐłĐ»ŃŹĐ´Đ°Ń‡Ń–Đ˛.' }, { "title": 'ĐźŃ€ĐľĐ´Đ°ĐşŃĐ˝', "desc": 'Đ—Đ˝Ń–ĐĽĐ°ĐąŃ‚Đµ Ń‚Đ° ĐĽĐľĐ˝Ń‚ŃĐąŃ‚Đµ ŃŹĐşŃ–ŃĐ˝Ń– ĐşĐ»Ń–ĐżĐ¸.' }, { "title": 'ĐśĐľĐ˝ĐµŃ‚Đ¸Đ·Đ°Ń†Ń–ŃŹ', "desc": 'ĐźĐµŃ€ĐµŃ‚Đ˛ĐľŃ€ŃŽĐąŃ‚Đµ ĐżĐµŃ€ĐµĐłĐ»ŃŹĐ´Đ¸ Đ˝Đ° Đ´ĐľŃ…Ń–Đ´.' } ] },
        { "id": 'ecom', "icon": 'đź›Ťď¸Ź', "title": 'E-commerce', "shortDesc": 'ĐźŃ€ĐľĐ´Đ°Đ˛Đ°ĐąŃ‚Đµ Ń„Ń–Đ·Đ¸Ń‡Đ˝Ń– Ń‚ĐľĐ˛Đ°Ń€Đ¸ ĐżĐľ Đ˛ŃŃŚĐľĐĽŃ ŃĐ˛Ń–Ń‚Ń Đ±ĐµĐ· ŃĐşĐ»Đ°Đ´Ń.', "fullDesc": 'Đ—Đ°ĐżŃŃŃ‚Ń–Ń‚ŃŚ Đ´Ń€ĐľĐżŃĐ¸ĐżĐżŃ–Đ˝Đł Đ°Đ±Đľ Đ±Ń€ĐµĐ˝Đ´ĐľĐ˛Đ¸Đą ĐĽĐ°ĐłĐ°Đ·Đ¸Đ˝. Đ’Đ¸Đ˛Ń‡Ń–Ń‚ŃŚ ĐżĐľŃŃĐş ĐżŃ€ĐľĐ´ŃĐşŃ‚Ń–Đ˛, Đ˛Ń–Đ´Đ˝ĐľŃĐ¸Đ˝Đ¸ Đ· ĐżĐľŃŃ‚Đ°Ń‡Đ°Đ»ŃŚĐ˝Đ¸ĐşĐ°ĐĽĐ¸ Ń‚Đ° ŃŹĐş ŃŃ‚Đ˛ĐľŃ€Đ¸Ń‚Đ¸ ĐşĐľĐ˝Đ˛ĐµŃ€ŃŃ–ĐąĐ˝Đ¸Đą ĐĽĐ°ĐłĐ°Đ·Đ¸Đ˝ Đ˝Đ° Shopify.', "steps": [ { "title": 'ĐźĐľŃŃĐş ĐźŃ€ĐľĐ´ŃĐşŃ‚Ń', "desc": 'Đ—Đ˝Đ°ĐąĐ´Ń–Ń‚ŃŚ Đ˛Đ¸ĐłŃ€Đ°ŃĐ˝Ń– Ń‚ĐľĐ˛Đ°Ń€Đ¸.' }, { "title": 'ĐˇŃ‚Đ˛ĐľŃ€ĐµĐ˝Đ˝ŃŹ ĐśĐ°ĐłĐ°Đ·Đ¸Đ˝Ń', "desc": 'ĐˇŃ‚Đ˛ĐľŃ€Ń–Ń‚ŃŚ ŃĐ°ĐąŃ‚ Đ· Đ˛Đ¸ŃĐľĐşĐľŃŽ ĐşĐľĐ˝Đ˛ĐµŃ€ŃŃ–Ń”ŃŽ.' }, { "title": 'Đ—Đ°ĐżŃŃĐş', "desc": 'Đ—Đ°Đ»ŃŃ‡Đ°ĐąŃ‚Đµ Ń‚Ń€Đ°Ń„Ń–Đş Ń‚Đ° Đ˛Đ¸ĐşĐľĐ˝ŃĐąŃ‚Đµ Đ·Đ°ĐĽĐľĐ˛Đ»ĐµĐ˝Đ˝ŃŹ.' } ] }
    ]
}

# Packages Data without corruption
packages_data = {
    "en": {
        "starter": { "features": ['Basic Course Access', 'Video Lessons', 'Standard Support', 'Weekly Updates'] },
        "growth": { "features": ['Everything in Starter', 'Community Access', '<strong>Advanced Strategies</strong>', 'Live Q&A Recordings', 'Case Studies'] },
        "elite": { "features": ['Everything in Growth', '<strong>AI Automation Tools</strong>', 'Exclusive Network', 'Private Mastermind', 'Priority Support'] }
    },
    "sl": {
        "starter": { "features": ['Dostop do osnovnih teÄŤajev', 'Video lekcije', 'Osnovna podpora', 'Tedenske posodobitve'] },
        "growth": { "features": ['Vse iz ZaÄŤetnega', 'Dostop do skupnosti', '<strong>Napredne strategije</strong>', 'Posnetki Q&A', 'Ĺ tudije primerov'] },
        "elite": { "features": ['Vse iz Naprednega', '<strong>AI Orodja & Avtomatizacija</strong>', 'Ekskluzivna mreĹľa', 'Zasebni Mastermind', 'Prioritetna podpora'] }
    },
    "sq": {
        "starter": { "features": ['Hyrje nĂ« Kursin BazĂ«', 'Leksione Video', 'MbĂ«shtetje Standarde', 'PĂ«rditĂ«sime Javore'] },
        "growth": { "features": ['GjithĂ§ka nĂ« Fillestar', 'Hyrje nĂ« Komunitet', '<strong>Strategji tĂ« Avancuara</strong>', 'Regjistrime Pyetje-PĂ«rgjigje', 'Raste Studimi'] },
        "elite": { "features": ['GjithĂ§ka nĂ« Rritje', '<strong>Mjete Automatizimi AI</strong>', 'Rrjet Ekskluziv', 'Mastermind Privat', 'MbĂ«shtetje Prioritare'] }
    },
    "ar": {
        "starter": { "features": ['ŮŘµŮŮ„ Ů„Ů„ŘŻŮŘ±Ř© Ř§Ů„ŘŁŘłŘ§ŘłŮŠŘ©', 'ŘŻŘ±ŮŘł ŮŮŠŘŻŮŠŮ', 'ŘŻŘąŮ… Ů‚ŮŠŘ§ŘłŮŠ', 'ŘŞŘ­ŘŻŮŠŘ«Ř§ŘŞ ŘŁŘłŘ¨ŮŘąŮŠŘ©'] },
        "growth": { "features": ['ŮŮ„ Ř´ŮŠŘˇ ŮŮŠ Ř§Ů„Ů…Ř¨ŘŞŘŻŘ¦', 'ŮŘµŮŮ„ Ů„Ů„Ů…Ř¬ŘŞŮ…Řą', '<strong>Ř§ŘłŘŞŘ±Ř§ŘŞŮŠŘ¬ŮŠŘ§ŘŞ Ů…ŘŞŮ‚ŘŻŮ…Ř©</strong>', 'ŘŞŘłŘ¬ŮŠŮ„Ř§ŘŞ ŘŁŘłŘ¦Ů„Ř© ŮŘŁŘ¬ŮŘ¨Ř©', 'ŘŻŘ±Ř§ŘłŘ§ŘŞ Ř­Ř§Ů„Ř©'] },
        "elite": { "features": ['ŮŮ„ Ř´ŮŠŘˇ ŮŮŠ Ř§Ů„Ů†Ů…Ů', '<strong>ŘŁŘŻŮŘ§ŘŞ ŘŁŘŞŮ…ŘŞŘ© Ř§Ů„Ř°ŮŘ§Řˇ Ř§Ů„Ř§ŘµŘ·Ů†Ř§ŘąŮŠ</strong>', 'Ř´Ř¨ŮŘ© Ř­ŘµŘ±ŮŠŘ©', 'Ů…Ř§ŘłŘŞŘ± Ů…Ř§ŮŠŮ†ŘŻ Ř®Ř§Řµ', 'ŘŻŘąŮ… Ř°Ů ŘŁŮŮ„ŮŮŠŘ©'] }
    },
    "be": {
        "starter": { "features": ['Toegang tot Basiscursus', 'Videolessen', 'Standaard Ondersteuning', 'Wekelijkse Updates'] },
        "growth": { "features": ['Alles in Starter', 'Toegang tot Community', '<strong>Geavanceerde StrategieĂ«n</strong>', 'Live Q&A Opnames', 'Case Studies'] },
        "elite": { "features": ['Alles in Groei', '<strong>AI Automatiseringstools</strong>', 'Exclusief Netwerk', 'PrivĂ© Mastermind', 'Prioriteit Ondersteuning'] }
    },
    "bs": {
        "starter": { "features": ['Pristup Osnovnom Kursu', 'Video Lekcije', 'Standardna PodrĹˇka', 'SedmiÄŤna AĹľuriranja'] },
        "growth": { "features": ['Sve u PoÄŤetnom', 'Pristup Zajednici', '<strong>Napredne Strategije</strong>', 'Snimci Q&A', 'Studije SluÄŤaja'] },
        "elite": { "features": ['Sve u Naprednom', '<strong>AI Alati za Automatizaciju</strong>', 'Ekskluzivna MreĹľa', 'Privatni Mastermind', 'Prioritetna PodrĹˇka'] }
    },
    "zh": {
        "starter": { "features": ['ĺźşçˇ€čŻľç¨‹č®żé—®', 'č§†é˘‘čŻľç¨‹', 'ć ‡ĺ‡†ć”ŻćŚ', 'ćŻŹĺ‘¨ć›´ć–°'] },
        "growth": { "features": ['ĺŚ…ĺ«ĺ…Ąé—¨ç‰ć‰€ćś‰ĺ†…ĺ®ą', 'ç¤ľĺŚşč®żé—®', '<strong>é«çş§ç­–ç•Ą</strong>', 'ç›´ć’­é—®ç­”ĺ˝•ĺŹ', 'ćˇäľ‹ç ”ç©¶'] },
        "elite": { "features": ['ĺŚ…ĺ«ćé•żç‰ć‰€ćś‰ĺ†…ĺ®ą', '<strong>AI č‡ŞĺŠ¨ĺŚ–ĺ·Ąĺ…·</strong>', 'ä¸“ĺ±žç˝‘ç»ś', 'ç§äşşç­–ĺ’äĽš', 'äĽĺ…ć”ŻćŚ'] }
    },
    "hr": {
        "starter": { "features": ['Pristup osnovnom teÄŤaju', 'Video lekcije', 'Standardna podrĹˇka', 'Tjedna aĹľuriranja'] },
        "growth": { "features": ['Sve u PoÄŤetnom', 'Pristup zajednici', '<strong>Napredne strategije</strong>', 'Snimke Q&A', 'Studije sluÄŤaja'] },
        "elite": { "features": ['Sve u Naprednom', '<strong>AI alati za automatizaciju</strong>', 'Ekskluzivna mreĹľa', 'Privatni Mastermind', 'Prioritetna podrĹˇka'] }
    },
    "cs": {
        "starter": { "features": ['PĹ™Ă­stup k zĂˇkladnĂ­mu kurzu', 'Video lekce', 'StandardnĂ­ podpora', 'TĂ˝dennĂ­ aktualizace'] },
        "growth": { "features": ['VĹˇe ve Start', 'PĹ™Ă­stup ke komunitÄ›', '<strong>PokroÄŤilĂ© strategie</strong>', 'ZĂˇznamy Q&A', 'PĹ™Ă­padovĂ© studie'] },
        "elite": { "features": ['VĹˇe v RĹŻstu', '<strong>AI AutomatizaÄŤnĂ­ nĂˇstroje</strong>', 'ExkluzivnĂ­ sĂ­ĹĄ', 'SoukromĂ˝ Mastermind', 'PrioritnĂ­ podpora'] }
    },
    "nl": {
        "starter": { "features": ['Toegang tot Basiscursus', 'Videolessen', 'Standaard Ondersteuning', 'Wekelijkse Updates'] },
        "growth": { "features": ['Alles in Starter', 'Toegang tot Community', '<strong>Geavanceerde StrategieĂ«n</strong>', 'Live Q&A Opnames', 'Case Studies'] },
        "elite": { "features": ['Alles in Groei', '<strong>AI Automatiseringstools</strong>', 'Exclusief Netwerk', 'PrivĂ© Mastermind', 'Prioriteit Ondersteuning'] }
    },
    "fr": {
        "starter": { "features": ['AccĂ¨s Cours De Base', 'LeĂ§ons VidĂ©o', 'Support Standard', 'Mises Ă  Jour Hebdo'] },
        "growth": { "features": ['Tout dans DĂ©butant', 'AccĂ¨s CommunautĂ©', '<strong>StratĂ©gies AvancĂ©es</strong>', 'Enregistrements Q&A', 'Ă‰tudes de Cas'] },
        "elite": { "features": ['Tout dans Croissance', '<strong>Outils Automation IA</strong>', 'RĂ©seau Exclusif', 'Mastermind PrivĂ©', 'Support Prioritaire'] }
    },
    "de": {
        "starter": { "features": ['Zugang Basiskurs', 'Videolektionen', 'Standard Support', 'WĂ¶chentliche Updates'] },
        "growth": { "features": ['Alles in Starter', 'Community Zugang', '<strong>Fortgeschrittene Strategien</strong>', 'Live Q&A Aufnahmen', 'Fallstudien'] },
        "elite": { "features": ['Alles in Wachstum', '<strong>AI Automatisierungstools</strong>', 'Exklusives Netzwerk', 'Private Mastermind', 'PrioritĂ¤ts-Support'] }
    },
    "mk": {
        "starter": { "features": ['ĐźŃ€Đ¸ŃŃ‚Đ°Đż Đ´Đľ ĐľŃĐ˝ĐľĐ˛ĐµĐ˝ ĐşŃŃ€Ń', 'Đ’Đ¸Đ´ĐµĐľ Đ»ĐµĐşŃ†Đ¸Đ¸', 'ĐˇŃ‚Đ°Đ˝Đ´Đ°Ń€Đ´Đ˝Đ° ĐżĐľĐ´Đ´Ń€ŃĐşĐ°', 'ĐťĐµĐ´ĐµĐ»Đ˝Đ¸ Đ°Đ¶ŃŃ€Đ¸Ń€Đ°ŃšĐ°'] },
        "growth": { "features": ['ĐˇĂ¨ Đ˛Đľ ĐźĐľŃ‡ĐµŃ‚ĐµĐ˝', 'ĐźŃ€Đ¸ŃŃ‚Đ°Đż Đ´Đľ Đ·Đ°ĐµĐ´Đ˝Đ¸Ń†Đ°', '<strong>ĐťĐ°ĐżŃ€ĐµĐ´Đ˝Đ¸ ŃŃ‚Ń€Đ°Ń‚ĐµĐłĐ¸Đ¸</strong>', 'ĐˇĐ˝Đ¸ĐĽĐşĐ¸ ĐľĐ´ Q&A', 'ĐˇŃ‚ŃĐ´Đ¸Đ¸ Đ˝Đ° ŃĐ»ŃŃ‡Đ°Ń'] },
        "elite": { "features": ['ĐˇĂ¨ Đ˛Đľ ĐťĐ°ĐżŃ€ĐµĐ´ĐµĐ˝', '<strong>AI ĐĐ»Đ°Ń‚ĐşĐ¸ Đ·Đ° Đ°Đ˛Ń‚ĐľĐĽĐ°Ń‚Đ¸Đ·Đ°Ń†Đ¸ŃĐ°</strong>', 'Đ•ĐşŃĐşĐ»ŃĐ·Đ¸Đ˛Đ˝Đ° ĐĽŃ€ĐµĐ¶Đ°', 'ĐźŃ€Đ¸Đ˛Đ°Ń‚ĐµĐ˝ Mastermind', 'ĐźŃ€Đ¸ĐľŃ€Đ¸Ń‚ĐµŃ‚Đ˝Đ° ĐżĐľĐ´Đ´Ń€ŃĐşĐ°'] }
    },
    "mt": {
        "starter": { "features": ['AÄ‹Ä‹ess gÄ§all-Kors BaĹĽiku', 'Lezzjonijiet tal-Vidjo', 'AppoÄˇÄˇ Standard', 'AÄˇÄˇornamenti ta\' kull ÄˇimgÄ§a'] },
        "growth": { "features": ['Kollox fil-Bidu', 'AÄ‹Ä‹ess gÄ§all-KomunitĂ ', '<strong>StrateÄˇiji Avvanzati</strong>', 'ReÄˇistrazzjonijiet Q&A', 'Studji ta\' KaĹĽijiet'] },
        "elite": { "features": ['Kollox fit-Tkabbir', '<strong>GÄ§odod ta\' Awtomazzjoni AI</strong>', 'Netwerk Esklussiv', 'Mastermind Privat', 'AppoÄˇÄˇ ta\' PrijoritĂ '] }
    },
    "me": {
        "starter": { "features": ['Pristup osnovnom kursu', 'Video lekcije', 'Standardna podrĹˇka', 'Nedjeljna aĹľuriranja'] },
        "growth": { "features": ['Sve u PoÄŤetnom', 'Pristup zajednici', '<strong>Napredne strategije</strong>', 'Snimci Q&A', 'Studije sluÄŤaja'] },
        "elite": { "features": ['Sve u Naprednom', '<strong>AI alati za automatizaciju</strong>', 'Ekskluzivna mreĹľa', 'Privatni Mastermind', 'Prioritetna podrĹˇka'] }
    },
    "pt": {
        "starter": { "features": ['Acesso ao Curso BĂˇsico', 'Aulas em VĂ­deo', 'Suporte PadrĂŁo', 'AtualizaĂ§Ăµes Semanais'] },
        "growth": { "features": ['Tudo no Iniciante', 'Acesso Ă  Comunidade', '<strong>EstratĂ©gias AvanĂ§adas</strong>', 'GravaĂ§Ăµes de Q&A', 'Estudos de Caso'] },
        "elite": { "features": ['Tudo no Crescimento', '<strong>Ferramentas de AutomaĂ§ĂŁo IA</strong>', 'Rede Exclusiva', 'Mastermind Privado', 'Suporte PrioritĂˇrio'] }
    },
    "ru": {
        "starter": { "features": ['Đ”ĐľŃŃ‚ŃĐż Đş Đ±Đ°Đ·ĐľĐ˛ĐľĐĽŃ ĐşŃŃ€ŃŃ', 'Đ’Đ¸Đ´ĐµĐľŃŃ€ĐľĐşĐ¸', 'ĐˇŃ‚Đ°Đ˝Đ´Đ°Ń€Ń‚Đ˝Đ°ŃŹ ĐżĐľĐ´Đ´ĐµŃ€Đ¶ĐşĐ°', 'Đ•Đ¶ĐµĐ˝ĐµĐ´ĐµĐ»ŃŚĐ˝Ń‹Đµ ĐľĐ±Đ˝ĐľĐ˛Đ»ĐµĐ˝Đ¸ŃŹ'] },
        "growth": { "features": ['Đ’ŃŃ‘ Đ˛ ĐˇŃ‚Đ°Ń€Ń‚ĐľĐ˛ĐľĐĽ', 'Đ”ĐľŃŃ‚ŃĐż Đş ŃĐľĐľĐ±Ń‰ĐµŃŃ‚Đ˛Ń', '<strong>ĐźŃ€ĐľĐ´Đ˛Đ¸Đ˝ŃŃ‚Ń‹Đµ ŃŃ‚Ń€Đ°Ń‚ĐµĐłĐ¸Đ¸</strong>', 'Đ—Đ°ĐżĐ¸ŃĐ¸ Q&A', 'ĐšĐµĐąŃŃ‹'] },
        "elite": { "features": ['Đ’ŃŃ‘ Đ˛ Đ ĐľŃŃ‚Đµ', '<strong>ĐĐ˝ŃŃ‚Ń€ŃĐĽĐµĐ˝Ń‚Ń‹ ĐĐ-Đ°Đ˛Ń‚ĐľĐĽĐ°Ń‚Đ¸Đ·Đ°Ń†Đ¸Đ¸</strong>', 'Đ­ĐşŃĐşĐ»ŃŽĐ·Đ¸Đ˛Đ˝Đ°ŃŹ ŃĐµŃ‚ŃŚ', 'Đ§Đ°ŃŃ‚Đ˝Ń‹Đą Mastermind', 'ĐźŃ€Đ¸ĐľŃ€Đ¸Ń‚ĐµŃ‚Đ˝Đ°ŃŹ ĐżĐľĐ´Đ´ĐµŃ€Đ¶ĐşĐ°'] }
    },
    "sr": {
        "starter": { "features": ['Pristup osnovnom kursu', 'Video lekcije', 'Standardna podrĹˇka', 'Nedeljna aĹľuriranja'] },
        "growth": { "features": ['Sve u PoÄŤetnom', 'Pristup zajednici', '<strong>Napredne strategije</strong>', 'Snimci Q&A', 'Studije sluÄŤaja'] },
        "elite": { "features": ['Sve u Naprednom', '<strong>AI alati za automatizaciju</strong>', 'Ekskluzivna mreĹľa', 'Privatni Mastermind', 'Prioritetna podrĹˇka'] }
    },
    "sk": {
        "starter": { "features": ['PrĂ­stup k zĂˇkladnĂ©mu kurzu', 'Video lekcie', 'Ĺ tandardnĂˇ podpora', 'TĂ˝ĹľdennĂ© aktualizĂˇcie'] },
        "growth": { "features": ['VĹˇetko v Ĺ tart', 'PrĂ­stup ku komunite', '<strong>PokroÄŤilĂ© stratĂ©gie</strong>', 'ZĂˇznamy Q&A', 'PrĂ­padovĂ© ĹˇtĂşdie'] },
        "elite": { "features": ['VĹˇetko v Rast', '<strong>AI AutomatizaÄŤnĂ© nĂˇstroje</strong>', 'ExkluzĂ­vna sieĹĄ', 'SĂşkromnĂ˝ Mastermind', 'PrioritnĂˇ podpora'] }
    },
    "es": {
        "starter": { "features": ['Acceso Curso BĂˇsico', 'Video Lecciones', 'Soporte EstĂˇndar', 'Actualizaciones Semanales'] },
        "growth": { "features": ['Todo en Inicial', 'Acceso Comunidad', '<strong>Estrategias Avanzadas</strong>', 'Grabaciones Q&A', 'Estudios de Caso'] },
        "elite": { "features": ['Todo en Crecimiento', '<strong>Herramientas AutomatizaciĂłn IA</strong>', 'Red Exclusiva', 'Mastermind Privado', 'Soporte Prioritario'] }
    },
    "uk": {
        "starter": { "features": ['Đ”ĐľŃŃ‚ŃĐż Đ´Đľ Đ±Đ°Đ·ĐľĐ˛ĐľĐłĐľ ĐşŃŃ€ŃŃ', 'Đ’Ń–Đ´ĐµĐľŃŃ€ĐľĐşĐ¸', 'ĐˇŃ‚Đ°Đ˝Đ´Đ°Ń€Ń‚Đ˝Đ° ĐżŃ–Đ´Ń‚Ń€Đ¸ĐĽĐşĐ°', 'Đ©ĐľŃ‚Đ¸Đ¶Đ˝ĐµĐ˛Ń– ĐľĐ˝ĐľĐ˛Đ»ĐµĐ˝Đ˝ŃŹ'] },
        "growth": { "features": ['Đ’ŃĐµ Đ˛ ĐˇŃ‚Đ°Ń€Ń‚ĐľĐ˛ĐľĐĽŃ', 'Đ”ĐľŃŃ‚ŃĐż Đ´Đľ ŃĐżŃ–Đ»ŃŚĐ˝ĐľŃ‚Đ¸', '<strong>ĐźŃ€ĐľŃŃĐ˝ŃŃ‚Ń– ŃŃ‚Ń€Đ°Ń‚ĐµĐłŃ–Ń—</strong>', 'Đ—Đ°ĐżĐ¸ŃĐ¸ Q&A', 'ĐšĐµĐąŃĐ¸'] },
        "elite": { "features": ['Đ’ŃĐµ Đ˛ Đ ĐľŃŃ‚Ń–', '<strong>Đ†Đ˝ŃŃ‚Ń€ŃĐĽĐµĐ˝Ń‚Đ¸ Đ¨Đ†-Đ°Đ˛Ń‚ĐľĐĽĐ°Ń‚Đ¸Đ·Đ°Ń†Ń–Ń—</strong>', 'Đ•ĐşŃĐşĐ»ŃŽĐ·Đ¸Đ˛Đ˝Đ° ĐĽĐµŃ€ĐµĐ¶Đ°', 'ĐźŃ€Đ¸Đ˛Đ°Ń‚Đ˝Đ¸Đą Mastermind', 'ĐźŃ€Ń–ĐľŃ€Đ¸Ń‚ĐµŃ‚Đ˝Đ° ĐżŃ–Đ´Ń‚Ń€Đ¸ĐĽĐşĐ°'] }
    }
}

import io

def inject_content():
    try:
        # Read the file with UTF-8 encoding
        with io.open(path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Regular expression to replace contentData object
        # We look for 'const contentData = {' and the closing '};'
        content_pattern = re.compile(r'const contentData = \{.*?\};', re.DOTALL)
        
        # Convert dictionary to JS formatted string
        # We use ensure_ascii=False to keep the emojis and characters intact
        js_content_string = "const contentData = " + json.dumps(content_data, ensure_ascii=False, indent=4) + ";"
        
        # Fix JS syntax (keys in JSON are strings, but we want them to look like JS keys if possible, 
        # but valid JSON is also valid JS, so we keep it simple. Only change is double quotes to single if preferred, 
        # but standard JSON is fine for JS execution)
        
        # Replace in content
        new_content = content_pattern.sub(js_content_string, content)

        # Regular expression to replace packagesData object
        packages_pattern = re.compile(r'const packagesData = \{.*?\};', re.DOTALL)
        js_packages_string = "const packagesData = " + json.dumps(packages_data, ensure_ascii=False, indent=4) + ";"
        
        new_content = packages_pattern.sub(js_packages_string, new_content)

        # Write back with UTF-8
        with io.open(path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        
        print("Successfully restored content and packages data.")

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    inject_content()
